### ISSUE TITLE
When I do /plugins GriefPrevention is in red, plugin doesn't work, or create a folder in plugins folder.

### ISSUE THREAD

**Issue by InfernusLv** [GriefPrevention/GriefPrevention#1061]
Currently have found no fixes, last night I ran up the server with Grief Prevention and it was up and fully working, restarted the server, ran up next day and it's dead. It doesn't create a folder, but the interesting thing is I can do /help GriefPrevention and it still shows up the list of commands I've tried
- Deleting the Jar file and folder
- Removing other plugins to see if they we're interfering

Plugin list:
Literally EssentialsX
And GriefPrevention

**Comment by Jikoo** [comment]
When you see a plugin in red, it means that there was an error enabling. We can't tell what the error was without startup logs, so if you could provide those from a time where it failed, that would be great.

**Comment by RoboMWM** [comment]
The first step is to read your server logs, the next step is to make sure both your server and GP are up to date.

**Comment by InfernusLv** [comment]
> When you see a plugin in red, it means that there was an error enabling. We can't tell what the error was without startup logs, so if you could provide those from a time where it failed, that would be great.

How do I post server logs?

**Comment by InfernusLv** [comment]
> > When you see a plugin in red, it means that there was an error enabling. We can't tell what the error was without startup logs, so if you could provide those from a time where it failed, that would be great.
> 
> How do I post server logs?

Figured it out myself.
[latest.log](https://github.com/TechFortress/GriefPrevention/files/5394464/latest.log)

**Comment by Jikoo** [comment]
The problem is that your world is named "World." ending with a period. Periods in YAML paths indicate a new section, meaning your world is attempting to create an illegal path like this:
```YAML
worlds:
  World:
    : value
```

World names really should be alphanumeric only. While Bukkit technically allows the creation of worlds with any name the file system supports, as shown by this problem it's generally a really bad idea. Technically GP can support this, but I don't know if it should.

Re: uploading logs - generally a paste service like gist.github.com is preferable because we don't have to download the file and then open it to read it, saves a bit of time. Also, you included more than just startup, so you leaked a couple players' IP addresses. Recommend you edit to remove the log and then delete edit history for that comment.

**Comment by RoboMWM** [comment]
Yea, we're not going to be enabling bad file/folder naming habits to have a more complicated config (or use a different delimitator than the standard). Spaces already push the limit... which is also present in the name, `Main World.` (It's not just `World.` @jikoo)

We suggest renaming to `main_world`

Also, it's preferred to paste log directly or in a [gist](https://gist.github.com)
