### ISSUE TITLE
A mid-point between /accesstrust and /containertrust would be great

### ISSUE THREAD

**Issue by xenoflot** [GriefPrevention/GriefPrevention#1086]
Hi,

Firstly, Thanks so much for sharing your hard work for free.

Request 1
The use case I have is where untrusted players may visit my home (or villager hub), trade away, use the shared facilities (work benches, enchanting table etc.) but not access chests.  The existing options are lacking. Accesstrust doesn't permit workstation access and Containertrust permits pilfering from chests. If possible, it'd be great to have a trust command mid-way between /access and /container. Perhaps /workbenchtrust

Request 2
In researching this problem, I found a remark that "players may not be aware of the existence of /accesstrust and /containertrust, thus resulting in unknowns getting undesirable levels of access". I suggest this problem could be addressed by reworking the /trust command. Trust with an invalid argument sequence would present a message along the lines of "Please specify: /trust access <name>, /trust workbench <name>, /trust container <name> or /trust total <name>"

Request 3
In researching a related problem, I found an old comment on LockAllDoors and pressure plates. The comment was along the lines of players like to use pressure plates to detect mob movement for mob farms and whatnot. For the sake of letting our players build piston doors but also enjoy privacy in their homes, it would be great if we had the option to have the plugin differentiate between a un/trusted player activating the plate and a mob. 

Thanks for your consideration.

**Comment by Jikoo** [comment]
Please limit issues to one thing. Multiple issues are way better than a single issue with a list.

1) Teach people to use subclaims. You can easily create a small subclaim around your enchanting table and workbench that has `/containertrust public` so that players can access only those objects. If the facilities you want them to be able to use are too spead out, you could `/containertrust public` in the parent claim and create a subclaim they can't access over your storage room with `/restrictsubclaim` instead.
GP core is unlikely to add additional trust types. An addon would be capable of finer-tuned control, but currently GP is not in a great state for addons doing that level of tweaking.
2) Valid, maybe `/trust` should be `/buildtrust` and a new `/trust` should be introduced that requires the trust type as a parameter.
3) Please read section in [the FAQ](https://github.com/TechFortress/GriefPrevention/issues/752) about pressure plates and wooden buttons. If you need clarity I'm willing to explain in more detail feasibility and potential pitfalls.

**Comment by xenoflot** [comment]
Mate, I can't even teach people to not dig straight downward! Will post ideas separately in future.

Thanks for the suggestions on the subclaim system, I'll definitely use those ideas on the admin-run facilities. I still think it'd be a good idea to have a /trust workbench option. If my career in support has taught me one thing, it's that users are a special kind of stupid. GP has made the process about as simple as it can but visualising claims and subclaims still requires some imagination and managing multiple claims and subclaims is likely beyond the ability of some of our younger (preteen) players. 

Yes, the FAQ links the exact post I was referencing about pressure plates being used in mob traps. If it's not possible to determine whether a plate was activated by a player or mob then sure, that makes sense. But if the distinction can be made, it'd be a nice option to have. I'm sure there are scenarios both for and against so it's not a suggestion I'll fight and die for :)

Thanks for the quick reply.

**Comment by Jikoo** [comment]
Sorry I didn't get back to you sooner, been a touch busy and jammed this in my notification backlog.

Your 1 and 2 points would be resolved by an addon with a UI for finer-grained control, but unfortunately in current GP that is not easily possible without either breaking existing addons or sending incorrect denial messages.

Pressure plates can be determined between players and non-player sources, however, determining the source of the non-player source is difficult. What's the difference between allowing a player to trigger a plate and allowing a zombie chasing the player to trigger a plate? What about dropped items, either from a player or an entity death? While I do want to eventually submit a system to GP that would allow for that level of tracking (with assistance from addons to keep heavier checks optional), it's a long way out, and there are numerous easy ways to circumvent GP's current capabilities were pressure plates included. Rather than lull players into a false sense of security, GP opts to not prevent plate usage at all.

**Comment by xenoflot** [comment]
Ah yes, backwards compatibility is a pain.  Thanks for the responses.  I'll close this and leave you to it. Thanks for sharing your hard work with us!
