### ISSUE TITLE
Land claim commands not working despite owning golden shovel

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [GriefPrevention/GriefPrevention#1298]
### What happened:
I managed to get my golden shovel and tired right-clicking blocks to define the corners of the claim, but nothing happened. Additionally, the plugin fails to recognize when the player is holding a golden shovel.

### What was expected:
Gold and glowstone blocks to show up marking out my land claim

### Steps to reproduce:
1. Get a golden shovel
2. Right click two separate blocks with shovel in hand
3. Try to type "/new claim", still with shovel in hand
4. Receive error message "you must be holding a golden shovel to do that" despite holding a golden shovel

### Server and GriefPrevention version:
Name; (N/A, Server is private)
Version: Currently busy with college work, but will check later

### Plugin list (if applicable):
GriefPrevention 

### Debugging steps attempted

- [x] I tried making a claim with other shovels
- [ ] I checked the version of the plugin that was installed
- [x] I tried holding my shovel in my recessive/off hand

**Comment by bigpreshkt** [comment]
We're going to need the server version and Grief Prevention version, when you have a moment to supply them.

For "Name", I think we were looking for the server software name (e.g. Spigot, Paper, etc) not the name of your Minecraft server.

It's most likely that the claim modification tool has been changed in the config, but since you haven't supplied the config (deleted that bit of the template?) we can't tell.

The reference to "golden shovel" in the message you get is the default value of  the message `Messages.MustHoldModificationToolForThat` which hard-codes the tool name, which it would be nice to improve on one day to dynamically fetch the name of the configured tool.

The two tools (investigation and modification) are set by the following config settings, shown with their default values:

```yaml
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
```

So - check those settings, and change to GOLDEN_SHOVEL if that's the tool you want to be using, if not, then use whatever tool it's set to, and change the message for `Messages.MustHoldModificationToolForThat` to suit.

**Comment by bigpresh** [comment]
We're going to need the server version and Grief Prevention version, when you have a moment to supply them.

For "Name", I think we were looking for the server software name (e.g. Spigot, Paper, etc) not the name of your Minecraft server.

It's most likely that the claim modification tool has been changed in the config, but since you haven't supplied the config (deleted that bit of the template?) we can't tell.

The reference to "golden shovel" in the message you get is the default value of  the message `Messages.MustHoldModificationToolForThat` which hard-codes the tool name, which it would be nice to improve on one day to dynamically fetch the name of the configured tool.

The two tools (investigation and modification) are set by the following config settings, shown with their default values:

```yaml
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
```

So - check those settings, and change to GOLDEN_SHOVEL if that's the tool you want to be using, if not, then use whatever tool it's set to, and change the message for `Messages.MustHoldModificationToolForThat` to suit.

**Comment by TheNamesGregoryAndounuts** [comment]
It's a spigot server and as it turns out the tool was changed to wooden shovel. So everything's good now.

**Comment by bigpresh** [comment]
Excellent - thanks for coming back to us to confirm all's well!
