### ISSUE TITLE
Grief Prevention Breaks Redstone

### ISSUE THREAD

**Issue by oisin404** [GriefPrevention/GriefPrevention#1331]
I am a big redstone nerd... I recently installed grief prevention plugin after having multiple bases destroyed it worked great, until I tried to make a redstone torch key in my base. These are very simple and I knew I hadnt got it wrong so I did some testing and it turns out one of the key features or redstone is broken, I know about the piston thing and all where they dont work outside of claims but this was different basiclly inside and out of claims blocks where not getting powered so for example you couldnt put a repeater facing into a block and then a redstone line on the other because it wouldnt power. This is very strange and annoying anyone got a solution?

![upload_2021-4-1_18-43-27.png](https://user-images.githubusercontent.com/49750262/113334062-1f180500-931b-11eb-9e71-859d0f55d81a.png)

**Comment by bigpresh** [comment]
Are you sayin that redstone signals are not being transferred into a claim from outside (or from inside one to outside)?  If so,I believe redstone signals not travelling into/out of claims is a designed feature, so that people can't trigger stuff on the border of your claim from outside it.

Redstone contraptions within a claim should work just fine (and in fact do, I use plenty).

If your redstone is entirely within the claim and still not functioning as you expect, then please provide the details requested in the template - versions etc.

**Comment by WalshOisin** [comment]
> Are you sayin that redstone signals are not being transferred into a claim from outside (or from inside one to outside)? If so,I believe redstone signals not travelling into/out of claims is a designed feature, so that people can't trigger stuff on the border of your claim from outside it.
> 
> Redstone contraptions within a claim should work just fine (and in fact do, I use plenty).
> 
> If your redstone is entirely within the claim and still not functioning as you expect, then please provide the details requested in the template - versions etc.
No I tested both fully in and out of claims maybe is conflicting with other plugins.

**Comment by RoboMWM** [comment]
Please do not attempt to delete reported issues, the discussion provided may be of use to future users who may encounter similar issues.

I'm presuming the user has resolved this on his end, idk why he won't say why or how.

Re-instated the deleted (albeit invalidly-formatted) report.
