### ISSUE TITLE
UNCLAIMED BUG

### ISSUE THREAD

**Issue by giantfurkii** [GriefPrevention/GriefPrevention#1340]
![S1](https://user-images.githubusercontent.com/78488589/113676383-09149680-96c5-11eb-8b43-e8b1dee5b4ae.png)
![S2](https://user-images.githubusercontent.com/78488589/113676390-0b76f080-96c5-11eb-8153-5250227f2063.png)
Although the player throws claim, it appears as unclaimed on the bottom side, right-clicking with the bar shows that it is claim, but the player who is not in claim can open the chests.

**Comment by giantfurkii** [comment]
![S1](https://user-images.githubusercontent.com/78488589/113677824-a91eef80-96c6-11eb-900e-118bb283445a.png)
![S2](https://user-images.githubusercontent.com/78488589/113677834-ab814980-96c6-11eb-904a-f2bfdcab3ae0.png)

**Comment by giantfurkii** [comment]
config.yml
https://paste.ubuntu.com/p/sVyMJSWbCq/

**Comment by Jikoo** [comment]
The claim likely does not extend down to cover the chests. See #1260

**Comment by giantfurkii** [comment]
what is the solution ?

**Comment by Jikoo** [comment]
Claims don't always extend down to bedrock so that they don't inconvenience players who are making long underground tunnels. They only extend down a configured distance until the player places blocks below the claim's limits. You're seeing that in combination with a mistake of mine that lead the inspection tool to ignore height. The inspection tool is now fixed for next release. You can download a dev build off AppVeyor if it's a pressing problem for you.
