### ISSUE TITLE
Compatible?

### ISSUE THREAD

**Issue by Purdze** [GriefPrevention/GriefPrevention#145]
When using this plugin with Shopkeepers, When im trusted in someones land and try to create a shop, it says ' You don't have permission to do that'  On my own land it works

**Comment by bigpresh** [comment]
Never seen/used "Shopkeepers", so no idea I'm afraid.

There's no particular support in the GP core for it; it sounds like something that could be implemented by someone by writing some custom code to hook in to GP via its API.

However - looking for the cases where a "You don't have permission to do that" error would be emitted by GP, it looks like it'd only happen if you try to use GP's `buyclaimblocks` or`sellclaimblocks` commands without the `buysellclaimblocks` permission,  (EDIT: or their aliases, `buyclaim` and `sellclaim`)

Are you sure that the message is definitely coming from GP?

**Comment by bigpresh** [comment]
Ah - Shopkeepers contains that exact same error message, so it's entirely possible that you're seeing that error from Shopkeepers, not from GP: https://github.com/nisovin/Shopkeepers/blob/master/src/main/java/com/nisovin/shopkeepers/Settings.java#L246 :

> public static String msgNoPermission = "&cYou don't have the permission to do that.";

And that message will be emitted if the "shop type" is empty: https://github.com/nisovin/Shopkeepers/blob/17f82c4c237928f02857c087f8a00cfd7fcf1e98/src/main/java/com/nisovin/shopkeepers/CreateListener.java#L93 within Shopkeepers' `PlayerInteractEvent` handler - so I suspect that there's an unintended interaction, perhaps GP is cancelling the interaction event because of a lack of permissions and causing Shopkeepers to complain (note that Shopkeepers `PlayerInteractEvent` handler will still receive cancelled events because they said `ignoreCancelled = false`) or Shopkeepers is cancelling it and causing GP to later complain.

You could try using `/shopkeepers debug` to see if anything useful is output by that plugin when you try to create a shop.

At this point, I'm fairly confident that this isn't a Grief Prevention problem, and thus I'm going to close the ticket, but if it turns out to be something we could fix, I'd be happy to have a look.  If the Shopkeepers dev is interested in debugging and working with us, if there's an easy solution I'm sure we could work something out.
