### ISSUE TITLE
CLAIM DELETE

### ISSUE THREAD

**Issue by giantfurkii** [GriefPrevention/GriefPrevention#1635]
I want the claims of players who have not been in the game for 10 days to be deleted.

Where is it set up ?

**Comment by bigpresh** [comment]
https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#expiring-inactive-claims

**Comment by giantfurkii** [comment]
https://prnt.sc/1xgyvgb

**Comment by giantfurkii** [comment]
Although the settings are correct, the player's claim has not been deleted.

**Comment by bigpresh** [comment]
How many accrued/bonus claim blocks does the claim's owner have (see `/claimslist PlayerName`)?  Could they have more blocks than your `ExceptWhenOwnerHas{Total,Bonus}ClaimBlocks` settings?

Does anything appear in your server's console log regarding expiration?  (BTW, the job runs periodically, and if I remember rightly it picks a claim more or less at random to check, so it isn't like you can expect an "expired" claim to disappear immediately as soon as its threshold is reached)

**Comment by giantfurkii** [comment]
https://prnt.sc/1xx11nd

**Comment by giantfurkii** [comment]
I want it to be deleted after 10 days no matter what, how do I set it up?

**Comment by bigpresh** [comment]
So they have >30k bonus blocks; what is your `ExceptWhenOwnerHasBonusClaimBlocks` setting set to?  If it's less than 30k, that's why.  If you set it to a really large value, those claims should eventually disappear.  As I mentioned before, they will not disappear exactly when the age is reached, because they're checked in the background somewhat randomly, but will eventually get removed.

**Comment by giantfurkii** [comment]
ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000

**Comment by giantfurkii** [comment]
how many should I set to be deleted after 10 days?

**Comment by bigpresh** [comment]
Basically, claims are exempt from being automatically dropped if the owner's accrued blocks from play total is higher than `ExceptWhenOwnerHasTotalClaimBlocks`, or if their bonus claim blocks total is higher than `ExceptWhenOwnerHasBonusClaimBlocks`.

So, if a player has 30k bonus blocks, and your `ExceptWhenOwnerHasBonusClaimBlocks` setting is set to 5k, then, yes, their claims are very much exempt from being dropped.

If you set those values to something rather high (say, 100000 maybe?) then the claims should start being dropped over time.

As an aside for personal opinion, 10 days is a very, very short time for most Minecraft servers, though, and would very much make me not want to play on a server like that, but maybe your server has some particularly unusual needs.  It could make sense with the exemption settings we're talking about left alone (particularly the total claim blocks one) as then players who'd played for a little then moved on have their stuff unclaimed, but players who'd played for longer, invested time and effort, and then are e.g. busy or on holiday for two weeks don't lose theirs.

**Comment by giantfurkii** [comment]
If they log in to the game within 10 Days, the claim will not be deleted, right?

**Comment by bigpresh** [comment]
> If they log in to the game within 10 Days, the claim will not be deleted, right?

Correct.

Periodically claims are inspected to see if they're eligible to be dropped - it first [checks if the player is exempt due to their number of blocks](https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/CleanupUnusedClaimPreTask.java#L60-L66), and if not, then goes off and  [checks to see if the player has been online more recently than the `AllClaimDays` setting](https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/CleanupUnusedClaimTask.java#L77-L84); if they've played more recently than that threshold, their claims won't be removed (and it wouldn't have even got as far as that check if they were exempted because they had more bonus/total blocks than the `ExceptWhenOwnerHas{Total,Bonus}ClaimBlocks` settings).

**Comment by giantfurkii** [comment]
![image](https://user-images.githubusercontent.com/78488589/140018068-5a565874-c7e8-44cc-9d3b-dc7f928a6505.png)
I did what they said, but the claims are still not deleted.

![image](https://user-images.githubusercontent.com/78488589/140018129-f343bb0a-a05a-4175-b7f7-5890c87f1e50.png)

**Comment by giantfurkii** [comment]
hey
