### ISSUE TITLE
This plugin is terrible

### ISSUE THREAD

**Issue by Techno1102** [GriefPrevention/GriefPrevention#168]
As soon as I downloaded this plugin, all of my redstone creations broke. So I went to my backup files and realized that I had not backed up in a while. So thanks to this idiotic plugin, my world has been ruined.

**Comment by MrPowerGamerBR** [comment]
I doubt GriefPrevention would magically break every redstone mechanism, in worst case it would just make pistons stop working until you reclaim the area. (which is a feature in GriefPrevention)

Anyway, that isn't a plugin issue, and it also isn't the plugin's fault that you didn't backup your worlds.

**Comment by Techno1102** [comment]
1. All of my creations have pistons in it do that's why
2. Where did it say that it would break pistons?
3. I don't need your comment about me not backing up my world so you can shut up

**Comment by MrPowerGamerBR** [comment]
@Techno1102 it is shown in the video and in the plugin description under the "It's IMPOSSIBLE to grief a land claim." section within the Spigot's (and Bukkit's) resource page. (I may be misremembering things but afaik the video does say that, I would double check but I'm not in a place with a good limitless internet connection so...)

https://www.spigotmc.org/resources/griefprevention.1884/

Also, telling me to shut up won't magically fix your world you know? 😛 Just because this plugin has a feature agaisnt griefing (which you can disable in GriefPrevention's config files, it is called `LimitPistonsToLandClaims`) doesn't mean that it is "terrible". 😉

**Comment by Techno1102** [comment]
1. Why would they have that. That's retarded...
2. I'll tell you to shut up if I want to. Because it will solve my problem. You.
3. Also because it breaks pistons is a terrible feature in this plugin so it does mean that.

**Comment by bigpresh** [comment]
I suggest you unload GriefPrevention, and take your vitriol elsewhere.

Alternatively, you could read the documentation to find out what it does, and how to use it, and use it appropriately.

**Comment by RoboMWM** [comment]
> As soon as I downloaded this plugin, all of my redstone creations broke.

GriefPrevention does not mess with redstone in any way. It also doesn't do any sort of cleanup unless you've abandoned a claim in a creative world.

> So I went to my backup files and realized that I had not backed up in a while.

Can't help you there. ¯\\_(ツ)_/¯ Testing/checking backups every now and then might help. "An untested backup is not a backup at all."

> All of my creations have pistons in it do that's why

A quick look at the config and documentation would instantly reveal piston-based protections. Big_Scary's has pistons disabled outside of claims by default (i.e. this is configurable) for performance reasons - the plugin wouldn't have to check for every extend and retract whether it's trying to pull/push a block into/out of a claim.
