### ISSUE TITLE
Players can steal items from claims with hopper_minecart

### ISSUE THREAD

**Issue by AmazedMender16** [GriefPrevention/GriefPrevention#1744]
### Observed Behavior

Untrusted (anyone) can steal items from players their chests using hopper_minecart.

### Expected Behavior

It shouldn't be possible to push minecarts into claims, or push them out of it.

### Reproduction steps

1. Place a chest 1 block above the ground, so that a hopper_minecart can fit below it
2. Claim the chest from Account 1
3. Use account 2 to push a hopper_minecart into the claim, under the chest
4. Push the minecart with account 2 outside of the claim
5. Open the minecart
6. Profit, you just stole all itmes

### Server version

```shell
git-Paper-408
```

### GriefPrevention version

```shell
16.18-RC1
16.18-RC1-13-gdbbd276
```

### Configuration

```yaml
Default config
```

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by bigpresh** [comment]
I think preventing this by checking minecart movements would be quite expensive (and might break existing mechanics).  Catching item transfer events as the item is about to be transferred could work, but at that point, I'm not sure you can realistically tell the difference between a hopper minecart that's supposed to be there (e.g. a farm system, etc) and one that someone has pushed in to the claim - and firing a check on every item transfer event would still likely be a little expensive.

It's quite simple to not have chests with air gaps under close to the edge of a claim / outside any buildings, so it is quite an unusual situation that anyone would fall afoul of this I think.

**Comment by Jikoo** [comment]
This has been suggested in the past in #985 - unfortunately, the InventoryMoveItemEvent is fired incredibly often and causes a lot of server load. As a result, Paper actually has a config to prevent the event from firing entirely (because it can cause lag even without any listeners doing additional calculation), which means this wouldn't even work on some server configurations.

If someone does want to take a stab at this, it's a complex beast of an idea:

1. Carts need to track ownership. This is tied to a relatively complex ownership system I've been thinking about writing for GP that would simplify a lot of logic for determining action owner across various events, but could definitely be implemented separately.
   * Either the person who placed it or the owner of the claim it spawned in (though tracking dispenser ownership may also be a good idea to prevent subclaim abuse)
   * Ownership should be transferred if the original owner transfers the containing claim, the area is claimed over, or if the owner is untrusted to prevent contraptions being arbitrarily destroyed on untrust/transfer
     * Ex: pay someone for a complex redstone structure involving hopper minecarts, structure immediately breaks because hopper minecarts no longer work.
2. Carts should track previous attempts.
   * Prevent repeat success queries
   * This will cause edge cases due to trust changes and potentially not being in the claim at the time, should probably also track time and allow rechecking every X time (15 seconds? 1 minute? 5 minutes?)
3. Carts should be disabled on denial.
   * Prevent repeat denied queries
     * [HopperMinecart#setEnabled(boolean)](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/minecart/HopperMinecart.html#setEnabled(boolean))
   * This is a behavioral change that would break any excessively complex hopper cart structures spanning multiple claims, but the alternative is exclusively depending on previous attempt tracking, which would have a much higher performance impact when used maliciously.

> It's quite simple to not have chests with air gaps under close to the edge of a claim / outside any buildings, so it is quite an unusual situation that anyone would fall afoul of this I think.

Teaching users to build intelligently is really difficult (leaving padding on the edges of your claim, things of that nature) - your average MC user doesn't tend to listen to instructions well. While it is simple to prevent, a lot of users like to have a fence or wall under a chest for a mailbox and often don't have a step up around it. That said, in a solely GP environment, a mailbox would then be vulnerable because you'd have to /containertrust everyone for them to be able to put things into it anyway, so it's more likely that the people falling victim of this are the even less experienced people who haven't built any kind of proper base.

I am going to close this because it's been declined as a core feature in the past for performance concerns. As it's a suggestion and #985 exists, you should post your ideas there.
