### ISSUE TITLE
1.18 Pistons don't work in claims in negative Y values

### ISSUE THREAD

**Issue by digitalcrowd** [GriefPrevention/GriefPrevention#1746]
### Observed Behavior

When a player places a piston in a claim, it gives warning as if they don't have the area claimed, even though they have an active claim. Placing pistons in a postive Y value, doesn't give the error. Additionally, not only do they get the error message, but pistons don't work properly.

### Expected Behavior

Pistons to work.

### Reproduction steps

Place a piston in a negative Y value in the world in 1.18.1

### Server version

```shell
Latest Paper 1.181.1
```

### GriefPrevention version

```shell
GriefPrevention version 16.17.1-2b69191
```

### Configuration

```yaml
N/A
```

### Plugin list

```shell
N/A
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
Please post the configuration you omitted from the report. You likely have an old config and have not updated your claim max depth to allow claims to extend below 0. You may also be suffering from #1735, which has been fixed in the most recent dev build.

/e: For reference, since I see you're running the now quite outdated release build for 1.16, the dev build in question can be found [here](https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/42088141/artifacts).

**Comment by Jikoo** [comment]
Also, "latest" is never a version. While I don't think Paper version is particularly relevant in this case, the fact that you not only used "latest" but also have a typo in the actual version string is pretty indicative of why you shouldn't do that.

**Comment by digitalcrowd** [comment]
## This is my config for that value...  what it's always been.
    ExtendIntoGroundDistance: 300
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0

Am I messing something from the ref bug report, or do I need to get the dev version?

OHHH ... 0 is the Y value, not like 0 meaning unlimited depth. That is a little confusing. I'll change it to -100

**Comment by Jikoo** [comment]
This is why we have the config as a required field - those are not default values (at least, that extend into ground distance isn't, nor is depth as of when this issue was addressed in dev builds), and is the most common cause of similar issues.

Yes, you should at least update to 16.18-RC1 - there were a couple additional issues with negative coordinates that needed to be fixed, though since you have existing claims I strongly recommend the dev build linked instead so claims properly extend down further. There are also numerous 1.17/1.18 fixes.
