### ISSUE TITLE
residual claims after deleting plugin

### ISSUE THREAD

**Issue by zerevoidd** [GriefPrevention/GriefPrevention#1755]
### Observed Behavior

i tried temporarily deleting this plugin including all of the related files but the previously claimed area isnt going away, a player on my server claimed 0,0 and i removed the plugin (not for that reason) and nobody was able to break 0,0, and i keep respawning at one of my previous claims even with the plugin and data folder completely removed

### Expected Behavior

...

### Reproduction steps

...

### Stack trace or error log

```shell
...
```

### Server version

```shell
spigot 1.18
```

### GriefPrevention version

```shell
...
```

### Configuration

```yaml
...
```

### Plugin list

```shell
too many to list but none that would conflict with it
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by bigpresh** [comment]
Well, if GP isn't loaded, then it's obviously not GP's fault.  (Remember that it's not enough to just delete the plugin .jar - you'll need to restart the server afterwards of course)

0,0 is probably subject to vanilla spawn protection, look in `server.properties` for `spawn-protection=` and set its value to `0` if you want to disable vanilla spawn protection - otherwise that area around spawn will be protected, which is nothing at all to do with GP.

For quick reference from docs,
> The spawn-protection field in server.properties determines the side length of the square spawn protection area as 2x+1. Setting this to 0 or a negative value disables the spawn protection. A value of 1 protects a 3×3 square centered on the spawn point, 2 protects 5×5, 3 protects 7×7, etc. The area that it protects is (spawn-protectionx2 + 1)x(spawn-protectionx2 + 1). 

Also,

>  i keep respawning at one of my previous claims

Presumably at the location you used a bed?

Finally, if you want to make sure that claim data is gone, then rename/move/delete `plugins/GriefPreventionData` which contains all the claim data and config.
