### ISSUE TITLE
ClaimResizeEvent extends a depreciated event

### ISSUE THREAD

**Issue by akdukaan** [GriefPrevention/GriefPrevention#1791]
I noticed a warning with my plugin because I was using the depreciated ClaimModifiedEvent. I switched it to ClaimResizeEvent which I thought would've fixed the issue but it still thinks I'm registering a listener for the depreciated event. I'm assuming this is because ClaimResizeEvent extends the depreciated ClaimModifiedEvent, but not too sure if that's the issue or what the fix would be. Would it just be to have the ClaimModifiedEvent extend the ClaimResizeEvent instead of the other way around? And you'd also move over all the methods to the new class?

`
[04:24:00 WARN]: [GriefPreventionFlags] "GriefPreventionFlags v5.11.3-SNAPSHOT" has registered a listener for me.ryanhamshire.GriefPrevention.events.ClaimModifiedEvent on method "private void me.ryanhamshire.GPFlags.listener.PlayerListener.onChangeClaim(me.ryanhamshire.GriefPrevention.events.ClaimResizeEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Big_Scary, ShaneBee, DmitryRendov, DrBot].
`

GP version 16.17.1-42-g3562a23-dirty

**Comment by Jikoo** [comment]
Ah, it's because the HandlerList is the same for compatibility I believe. I had written a whole extensive thing for passing the registration but determined I was wrong and it was overkill. Heck. Also will look into whether it's possible to change that message about server performance.

**Comment by Badbird5907** [comment]
Hello, I'm also getting this issue when listening to ClaimResizeEvent.


![idea64_coV7aFX7Ye](https://user-images.githubusercontent.com/50347938/201541904-f457e3c3-d22c-4caa-a5d0-a20f5b03ea3c.png)
ignore the stack trace above, unrelated.

GP version: 16.18
Server Version:
```
[15:00:04 INFO]: Checking version, please wait...
[15:00:05 INFO]: This server is running Paper version git-Paper-270 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e22dacf)
You are running the latest version
Previous version: git-Paper-65 (MC: 1.19)
```
Plugins: `Plugins (5): Essentials, GriefPrevention, GriefPreventionTP, LuckPerms, Vault`

**Comment by Jikoo** [comment]
> Ah, it's because the HandlerList is the same for compatibility I believe.

This assumption by me was wrong, in case anyone runs into similar issues elsewhere. The warning would still have been printed if the class had its own HandlerList.

The warning is caused by `JavaPluginLoader#createRegisteredListeners`, which checks for `@Deprecated` superclasses. The message about server performance being impacted can be edited with a `@Warning` reason.
The `@Warning` must be on the same class that is `@Deprecated`, so you cannot override and hide the warning without deprecating the class doing the warning override. This could be an intermediary class so that the real and current class is not deprecated, but then you have to ensure users can't actually use it, likely by intentionally throwing errors when obtaining its HandlerList.
