### ISSUE TITLE
Add a ClaimBlockDeliveryEvent

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#18]
It's possible to add this ?
http://prnt.sc/cq1rb7
Thanks !

**Comment by bigpresh** [comment]
To save others loading the screenshot instead of seeing a description, what you're asking for is a variable claim blocks accrual rate and max claim block cap, based on the permission the user has, supporting any number of permissions.

I'm not sure how many people that would be useful to, or how difficult it would be to implement.

I know that there is, at least, some basic, albeit limited, support for variable accrual rate depending on permission, but it's limited to a pair of "faster" / "fastest" permissions, rather than infinitely variable.

This doesn't appear to be well-documented yet, but since 14.8 users with the permission `griefprevention.fastestaccrual` will get the rate specified by `blocksAccruedPerHour_fastest` in the config, and those with `griefprevention.fasteraccrual` get the rate specified by `blocksAccruedPerHour_faster` in the config.

**Comment by ghost** [comment]
I need more than 2 permissions

**Comment by RoboMWM** [comment]
Thought about this for a while, and I probably want to go the route of making this call a custom event, allowing addons to do what they wish when GP decides to deliver claim blocks. Will be accepting PRs to do this (until I get time to do it myself, of course).

**Comment by BillyGalbreath** [comment]
With the new system custom accruals are now set via an addon:

https://www.spigotmc.org/resources/gpaccruals.32122/

**Moderator edit**
In lieu of the resource being removed on spigot, the addon can be found here: https://github.com/TechFortress/GriefPrevention/discussions/2075

**Comment by Crytikill** [comment]
How would I go about setting the GPA/claim blocks per hour for each permission? Permissions: Member, VIP, etc... Please explain to me
