### ISSUE TITLE
Claim block allowance afk bypass

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#180]
### What behaviour is expected:
While idling/using antiafk hacks, players dont get claimblocks
### What behaviour is observed:
Hackers can bypass the anti-idling functionality using thing such as wurst antiafk ai mode
### Steps/models to reproduce:
Test greifprevention using wurst client, turn on anti-afk and check use ai, you get claimblocks

### Spigot/Craftbukkit/Paper and GriefPrevention version:
git-TacoSpigot-"99d21c3f" (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
gp 16.7.1

Should probably do deeper checking such as containers, mining, building, etc

**Comment by RoboMWM** [comment]
> Should probably do deeper checking such as containers, mining, building, etc

There's an infinite amount of things to check for (as well as potential false positives that I see with these examples). Unfortunately, the best we can do is make it difficult for afk clients to succeed, and this goes for any afk-detection system. If a bot can mimic a player doing random, various actions, it's not all that easy for an automated system to detect such a thing.

This would _somewhat_ be more suitable for an anticheat-like plugin. I say "somewhat" because it's not really any exploitation of the game mechanics itself, but it does fall in the "non-player-created" actions, so _some_ degree of pattern-checking could be implemented. Short of something akin to machine-learning though, this will only stop the simplest of afk bots.

I'd suggest plugins like AfkTerminator if you have issues with afk players...

**Comment by pedro751** [comment]
hi, in my server player who boigh ranks can stay afk without getting kicked but rhe players do not recieve claims while they are afk, any way to fix that?

**Comment by RoboMWM** [comment]
Your suggestion is a feature request and not related to the bug in question (yes mechanics are related, but the intent is not). Please consider reposting in the Discussions forum.
