### ISSUE TITLE
Unclaimed and reclaimed a 10K claim - now chests are unprotected

### ISSUE THREAD

**Issue by MegaMinerDL** [GriefPrevention/GriefPrevention#1832]
### Observed Behavior

On a server, I have a base with a 10K blocks claim and about 2-3 stacks of chests in my storage area.
I temporarily unclaimed my base, and claimed it again. Now other people on the server could open all my chests.
Clicking with the claim tool showed that my land is claimed, but the containers wouldn't protect!

Possible issue - too many chests on a too big claim? I claimed my 10k base back when it had one or two chests, and everything worked fine up until I unclaimed, even when I had 2-3 stacks chests.

Workaround - I unclaimed the base, and split it by claiming multiple seperate 2-3k chunks instead. Now all chests are in a single 1k claim and are protected.

No one else has had this issue to my knowledge.

### Expected Behavior

All containers should have been automatically protected in the claim, yet they were not upon re-claiming.

### Reproduction steps

Server where issue was observed: IDMC (IP 51.81.49.133:25592 | version 1.18.1)
I do not have access to files there so cannot do any testing with clean server / see configs / etc
unfortunately. But perhaps you can trace the issue to something?

I managed to get 10k+ claim blocks over time. Made a claim, but after re-claiming, the chests won't protect.
See server/plugin versions and issue description for info.
![Uploading 2022-03-09_17.17.49.png…]()

### Stack trace or error log

```shell
N/A *(no access/ likely a glitch without direct error log dumps)
```

### Server version

```shell
This server is running Paper version git-Paper-204 (MC:1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git:7b8e0c3)
You are 12 version(s) behind.
/Previous version: git-Paper-104 (MC: 1.18.1)/
```

### GriefPrevention version

```shell
52c8a81
```

### Configuration

```yaml
N/A *(no access to configuration files)
```

### Plugin list

```shell
(31:) advancedmotd, anticurse, auctionhouse, automaticbroadcast, buycraftx, chatcolor2, coreprotect, custompolls, decentholograms, essentials, essentials warpgui, essentials chat, essentials spawn, floodgate, geyser spigot, GRIEFPREVENTION, interaction visualizer, lite playtime rewards, lottery, luckperms, multiverse core, placeholder api, playtime, spark, tab, tradesystem, viaversion, wild, worldborder, world edit, world guard
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
Presuming that the chests were below the actual claim level, because that's the only reason they wouldn't be encompassed by the claim.
GP only automatically extends claims downward to cover builds in loaded chunks on claim creation. Excessively large claims may, as a result, not extend down properly when placed over existing builds. If you're trying to adjust a claim, it's much safer to resize rather than recreate. You can also resize your claim with points at an appropriately low Y level to cover your chests.

Would need more details about the build/claim creation process to be able to reproduce.

**Comment by MegaMinerDL** [comment]
I think this might be the issue. Look at the attached pictures for context on the build - when I wanted to claim the whole thing, I claimed by clicking the top corners of the dirt wall around the base. The chests were well below, inside the monument. Does this provide enough reference to attempt to reproduce and fix this issue?
![2022-03-11_17 25 09](https://user-images.githubusercontent.com/99270686/158077446-529f412c-88ce-4d4d-9e4d-09c5274e9b98.png)
![2022-03-06_16 49 06](https://user-images.githubusercontent.com/99270686/158077437-6051d2a3-fa1e-499b-9ab4-e025a00a97b0.png)
![2022-02-17_20 39 19](https://user-images.githubusercontent.com/99270686/158077416-86bf8e27-e17f-47a4-89a8-7c6e00674945.png)

**Comment by Jikoo** [comment]
Sorry it's been a hot minute since I got back to you. Definitely looks like there are areas where GP's automatic extension on creation could use improvement and I have some ideas for that, but not sure why that particular one wouldn't work right - it sure looks like it should be loaded even with very restrictive server settings.

**Comment by Jikoo** [comment]
Okay, looks like the search doesn't reset its X and Z coordinates when it finds a natural block and continues looking down. As a result, it's very possible to skip an entire chunk because there are no blocks that are clearly (in terms of belonging to a biome) player-placed blocks in a particular Y coordinate.

I don't think I'll be redoing the search to search unloaded chunks - that's not possible without a not insignificant amount of additional work for Spigot that I don't really have the drive to do - but I will submit a PR to rewrite the search system to be more thorough.
