### ISSUE TITLE
Plugin does not work - java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()

### ISSUE THREAD

**Issue by dermodmaster** [GriefPrevention/GriefPrevention#19]
Dear Plugin Team,
personally I like your plugin but it wont work on our server and i don't know why.

The plugin is "green" in our plugin list (/pl)

But if i type a command the plugin only put out:
_an internal error while occuried Attempting to perform this command_

In the attached server logs you can clearly identify the problem I think (/hope)

Full Server Log:
http://pastebin.com/kMSX8sie

Filtered Server Log:
http://pastebin.com/sT1Zfij6

I've tried version 13.1 & 13.2 on 3 different spigot 1.10 & 1.10.2 versions
and one time I've deactivated all other plugins except of WorldEdit, WorldGuard and dynmap.
# Version Info:

[INFO] This server is running CraftBukkit version git-Spigot-047f737-9558f31 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[INFO] Checking version, please wait...
[INFO] You are running the latest version

I don't understand how to fix...
Please help 👍 
Best regards 🎱

**Comment by RoboMWM** [comment]
Duplicate of #17

First of all, you should really fix the configs of your other plugins. Your start log has multiple plugins erroring because of invalid configs.

Second, please, please, if you can, update to Java 8. If you're on a shared host, please tell them to update. Java 7 is End-of-Life and vulnerable to security exploits (nor will receive any optimizations).

Third, if you _really truly_ cannot update to Java 8, download the Java 7 version of GriefPrevention.

**Comment by dermodmaster** [comment]
Thank you very much _-_
