### ISSUE TITLE
Moving from 16.18 to 16.18.2 beta on 1.18.2 PurPur breaks GP items, stopped the golden shovel and stick working all together

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#2190]
### Observed Behavior

After upgrading to 16.18.2 from 16.18 when using PurPur 1.18.2, the GriefPrevention items no longer work.

### Expected Behavior

For the items to work.

### Reproduction steps

1. Use 1.18.2 PurPur
2. Use vanilla GP 16.18.2 with no other plugins
3. Try and make a claim using the golden shovel

### Server version

```shell
1.18.2 PurPur Latest
```

### GriefPrevention version

```shell
16.18.2 Beta
```

### Configuration

```yaml
Entirely vanilla
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by TomLewis** [comment]
Just tested with 16.18.1 and items still work

**Comment by RoboMWM** [comment]
Start log would be interesting, cuz it may be possible that GP isn't even starting up.

**Comment by TomLewis** [comment]
So I just tested on another test server in a different environment and the same issue.
I removed the thousands of warnings about the claims not being in a the test server, database was copied from prod to test, that world isn't on it, same for siege, luckily there's an error with registering events! I hope this is the cause!

```[14:09:58] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention vda38fbd
[14:09:58] [Server thread/INFO]: [GriefPrevention] Error: Siege Configuration: There's no world named "PirateCraft_1_nether2".  Please update your config.yml.
[14:09:58] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.

- a ton of warnings about claims in other worlds not on this test server.

[14:10:00] [Server thread/INFO]: [GriefPrevention] 30519 total claims loaded.
[14:10:00] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[14:10:00] [Server thread/INFO]: [GriefPrevention] Successfully hooked into WorldGuard.
[14:10:00] [Server thread/INFO]: [GriefPrevention] Finished loading data (Database Mode).
[14:10:00] [Server thread/ERROR]: [GriefPrevention] Plugin GriefPrevention vda38fbd has failed to register events for class me.ryanhamshire.GriefPrevention.PlayerEventHandler because org/bukkit/event/player/PlayerSignOpenEvent does not exist.
[14:10:00] [Server thread/INFO]: [GriefPrevention] Boot finished.
```

If you want to test in-game I can send you an IP to our test server and whitelist so you can see yourself.

**Comment by QarthO** [comment]
Can you share the full server log? You can upload it to [mclogs](https://mclo.gs/) so it'll hide all sensitive data, then share the link here

**Comment by RoboMWM** [comment]
This issue confirms that https://github.com/GriefPrevention/GriefPrevention/pull/2192 was necessary. GP is no longer compatible with any version before 1.19.4.

Are there any fixes you're looking for in 16.18.2?

**Comment by Jikoo** [comment]
Interesting, that's absolutely my bad. I was aware Bukkit gracefully handles missing events, but I didn't realize it completely skips the entire listener. Moving it to a separate listener would solve this for 1.19/outdated 1.20.

**Comment by RoboMWM** [comment]
Feel free to do that for legacy. Only requirements for legacy is that compatibility with existing addons, config, and data structure is maintained.

**Comment by RoboMWM** [comment]
Am reclose this, only cuz it wouldn't target master branch. But PR can still reference and address.

**Comment by TomLewis** [comment]
That was a very fast diagnosis! Fantastic job guys! 

Do you want me to test a Dev build? I've lost the build server URL 🤣

Sorry this took me so long to update, irl just been long.

**Comment by Jikoo** [comment]
I think the org transfer at least partially broke Appveyor, but I'm not sure. At very least the legacy branch isn't configured to build, which does make some sense because of how it doesn't do a good job supporting branches. Makes it really hard to use as a CI sometimes because people don't read the branch tag before downloading "latest."

I think the best I personally could do would be set up Actions to be manually triggerable with an upload of the build. Then people could fork, build, and download it with a little technical knowledge. I won't be able to get to that until tonight at least, managed to squeeze that PR in over lunch.

**Comment by RoboMWM** [comment]
I had to configure appveyor to use new url, cuz it was 403'ing github's webhook otherwise. I have it configured to not build other branches, but I guess I can change that. Either way, is meant to be for quick and dirty "dev builds" and PR testing really. 

I think my primary concern was what Actions can be permitted to do; same reason why I didn't want Dependabot on this repo. Appveyor does everything outside of github so I have no worries about it inadvertently modifying branches or other whatnot. If you wanna do stuff on this front I guess you can open a new discussion about it if there isn't already one.

**Comment by QarthO** [comment]
> If you wanna do stuff on this front I guess you can open a new discussion about it if there isn't already one.

I created a discussion if we wanna talk about how we want to setup actions
https://github.com/GriefPrevention/GriefPrevention/discussions/2210
