### ISSUE TITLE
[Request] Slimefun Grappling Hook in Regions

### ISSUE THREAD

**Issue by whoshenry** [GriefPrevention/GriefPrevention#220]
### What behaviour is expected:
Not being able to use the grappling hook from Slimefun (or the multitool version) in or into a claimed region.
### What behaviour is observed:
Players can grappling hook into claimed regions.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
version git-Spigot-7754231-94b0980 (MC: 1.12.2)
GP - 16.7.1

I've put this as a suggestion on the Slimefun 4 github but it was immediately closed down without any comment and I saw you had some pull requests from Slimefun 4. I know this isn't an issue with GriefPrevention per say but I think it would be a good idea if players were unable to use the Grappling hook and potentially other items in GP claimed areas, is this a possibility?

**Comment by RoboMWM** [comment]
Lol, that's thebusybiscuit for you, he also insta-closed all of my bug reports and questions.

As much as he might not like it, the onus is on him - GP cannot tell if Slimefun is doing anything unless it sends some sort of event.

So, if he won't do it, either get someone to make a PR to add compatibility or an addon. Or fork it.

My PRs were to mavenize it so other developers can contribute easily. I would've contributed a few things but shortly after I PR'd those (which took a few days to sort out) I was busy with other life stuff and I'm still busy currently, lol. (I've also shifted my attention away from survival-modifications for now.)

**Comment by whoshenry** [comment]
Thanks for the reply, it's frustrating even making a suggestion to him, insta-closed.

Do you know of anyone who would be willing to make a PR for this? I don't really know many people in this area.

Thanks.

**Comment by RoboMWM** [comment]
Could try spigot's services section. https://www.spigotmc.org/forums/offering-developers.59/

**Comment by bigpresh** [comment]
I'm going to close this one since it's not a GP bug and I don't think it's an improvement that can be made in GP either; it might be doable by someone as a GP plugin if Slimefun triggers events that it could catch.  I don't know if it does so (I do see a [MultiBlockInteractEvent](https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Events/MultiBlockInteractEvent.java) event there, but I don't know in which situations that gets thown).

So, yeah, not something we can do in GP core, but if Slimefun fires events than someone could do something with them.
