### ISSUE TITLE
Improve claim expiration

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#24]
@Jikoo:

> That seems inefficient, when you thing about it - wouldn't it be better to check all players for whom there are data files rather than check each claim's owner, as each player might have several dozen claims?

Yes, that does seem rather inefficient. Not sure why he's checking random claims vs. a random player. However, I think the reasoning behind this is that people can set the expiration date far beyond what GP caches for PlayerData by default (it only caches PlayerData of players that have logged in within the last 90 days) - whereas all claims are cached. However, it is getting the claim owner anyways, cached or not - I guess his method is the more "RAM efficient" method. (This is also probably why he denied checking the last login date of trustees, since he'd have to load an indeterminate amount more PlayerData.)

How would you go about this?

**Comment by Jikoo** [comment]
Good reasoning. Honestly, it's not very intensive, just that it does potentially cause several repeated checks per-player, oftentimes in quick succession.

The only way I could see to work it without loading all player data would be to create a list or set of players to check data for based on owners of existing claims. That'd be a pretty negligible amount of extra memory I believe, could do some actual testing on that if really needed.

Either way, for me it's pretty much a non-issue - I'm small. I only have around 1000 claims, most active players have about 5. GP checks at a rate of 1 per minute, so it takes 16 hours to actually check them all. Checking players instead would be faster, certainly, but I easily complete a full check every day. I'd say whether or not it's worth bothering making any changes depends on numbers from larger servers.

**Comment by RoboMWM** [comment]
Also, some PlayerData files may simply be of inactive players who no longer own any claims.

**Comment by Jikoo** [comment]
I was assuming that rather than using PlayerData files it'd use the claim list to compile a list of player IDs. Yeah, you'd run into duplicates there, but you wouldn't be adding duplicate entries into the final set to actually check.

Here's a quick and dirty example that I'm pretty sure would work:

``` java
Set<UUID> playersWithClaims = GriefPrevention.instance.dataStore.claims.stream()
        .map(claim -> claim.ownerID).collect(Collectors.toCollection(HashSet<UUID>::new));
```

Obviously could be done in a Java 7-compatible manner, just would take a little more work to express.

Then simply do as before, except instead of passing a Claim, pass a UUID and go from there. Since the UUIDs are already in memory, they shouldn't consume more, though the Set itself will use a certain amount per entry.

The downside is that as the claims list is modified, the set is not updated, though it could be at regular intervals, such as every time a cycle completes.

**Comment by RoboMWM** [comment]
Just wanted to make clear that I am accepting PRs to implement this change; I personally don't have time at the moment to create and test myself. (As we can see, there's a couple of things to account for - server start time (i.e. don't schedule create list in onEnable), updating the list (or just recreating the list, whichever is more efficient/makes sense?), potentially accounting for and caching an "exclude" list of players who have reached the minimum blocks required to keep their claim(?), etc.)
