### ISSUE TITLE
Protected drops can be stolen via item merging

### ISSUE THREAD

**Issue by MithrandirCraft** [GriefPrevention/GriefPrevention#255]
### What behaviour is observed:
Protected drops can be stolen by stacking your own items on top.
### What behaviour is expected:
Items should either not stack, or still be protected.
### Steps/models to reproduce:
Just stack a item of the same type on top of a protected dropped item.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
GP: 16.7.1   
Spigot: git-Spigot-4bd94dc-4a03053 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

No errors, just natural vanilla behaviour overlaping yours.

**Comment by RoboMWM** [comment]
I'm guessing you mean merging, not stacking.

**Comment by RoboMWM** [comment]
I don't think an event is called when this happens?

So one way to go about this is to modify the names of the itemstacks directly to prevent merging. However, we are modifying the names, and I rather not try storing in metadata and attempting to replace, since a server restart/chunk unload will clear this metadata. Another way would be to prevent dropping items near protected items. This could potentially be circumvented via a player death, which causes their own items to drop next to the player.

A third way is to not use this at all and instead use something like SavageDeathChest.

**Comment by Jikoo** [comment]
[ItemMergeEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/ItemMergeEvent.html)

**Comment by RoboMWM** [comment]
Javadocs are not clear on the difference between getEntity and getTarget. My guess is the target will be the longer-living Item (which would be the original drop). Let me know if this fixes it.
