### ISSUE TITLE
Build error trying to sell Cocoa Bean

### ISSUE THREAD

**Issue by Bobobaal** [GriefPrevention/GriefPrevention#256]
### What behaviour is observed:
Right clicking a sign to sell Cocoa Beans using the Shop plugin. (https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/)
### What behaviour is expected:
A message that the item is sold. Instead GP error that you can't build on the claim.
### Steps/models to reproduce:
You need a buy shop for cocoa bean
Not being trusted on the claim and try to sell the cocoa bean by right clicking the sign

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Spigot: CraftBukkit version git-Spigot-4bd94dc-c765646 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
GP: 16.8

**Comment by RoboMWM** [comment]
Plugin either needs to listen before GP or you need to give /accesstrust. Or maybe it's checking GP permissions. Really not sure since it's premium, but there's multiple ways to fix this.

On a slight aside, I'm finishing up a shop plugin (that will be free) and will work with all region protection plugins the way shops should work.

**Comment by Bobobaal** [comment]
You can close this since another player found a solution I did not found.

**Comment by RoboMWM** [comment]
If you mind sharing what he found...

**Comment by Bobobaal** [comment]
Right clicking the sign with an empty hand while having the items in your inventory.
