### ISSUE TITLE
not  running with ctsnc

### ISSUE THREAD

**Issue by cknost** [GriefPrevention/GriefPrevention#268]
I can't use it with ctsns http://herbystar.eu/resources/ctsnc-animated-scoreboard-and-tablist-nametag-chat-protocol-hack.8/ every version.

**Comment by RoboMWM** [comment]
Likely not a GP issue, but you're going to have to actually fill out the template you deleted because you provided hardly any info.

**Comment by cknost** [comment]
ctsns saw the same thing... http://herbystar.eu/threads/ctsnc-animated-scoreboard-and-tablist-nametag-chat-protocol-hack.12/page-5#post-358

**Comment by bigpresh** [comment]
I assume you meant "ctsns said the same thing" - if so, from the forum thread you linked to, you said: "griefpreventation saw that the bug comes from you" - actually, no such thing was said.

It was pointed out that it's probably not GP's issue, but that we can't tell because you provided hardly any information - and still haven't done so.

From https://pastebin.com/wruKJndx it looks like you might be trying to use a recent GP version on an ancient 1.8.x MC server?  If that's the case, you'll need to use a GP version compatible with old Minecraft versions - see the releases page for the version each release works with, or see https://dev.bukkit.org/projects/grief-prevention/files - you probably want 13.9.1.
