### ISSUE TITLE
Flag 'interact-block-secondary'

### ISSUE THREAD

**Issue by TheNullablePrototype** [GriefPrevention/GriefPrevention#282]
/cf interact-block-secondary - this flag does not work for these blocks:
minecraft:enchanting_table, minecraft:crafting_table, mechanical_anvil, pixelmon:PC, pixelmon:Trade_machine, minecraft:anvil

**Comment by bigpresh** [comment]
I don't believe that GP has any such flags built in - there are plugins that offer it, though.

Are you, perchance, looking for the GriefPrevention version for Sponge-powered servers, which does have the /claimflag (/cf) command, among other stuff, rather than this, the Bukkit version, which doesn't?

**Comment by TheNullablePrototype** [comment]
We use Sponge as a server core. To be honest, I didn't really understand your question.

**Comment by bigpresh** [comment]
Sorry, maybe I wasn't clear - there's two versions of GriefPrevention - this one, that you've raised a ticket against, is for Bukkit servers; it doesn't support flags etc built-in.

There's also a version for Sponge-powered servers, which *does* have flags stuff built-in - it sounds like that's the version you're using, and thus the version you want to be raising a ticket against.  The developers of this Bukkit version have no connection with the other one, and are unlikely to be able to help you.

I think https://github.com/MinecraftPortCentral/GriefPrevention is the project you want.
