### ISSUE TITLE
Better support for altered mechanics

### ISSUE THREAD

**Issue by zedwick** [GriefPrevention/GriefPrevention#290]
I have created a plugin which allows for reading books in item frames by interacting with the item frame. I have it set up with lowest priority, and it cancels the event so the item will not rotate in the frame, and then opens the book for reading.
Unfortunately as GP also listens on lowest priority I cannot cancel the event before GP responds to it, so GP also informs the player that they have no build permission to the claim when the book opens. For this specific situation all I need is for the text to not be displayed.

I have one proposal to fix for this, but I am not sure it is the best way:

Change the EventPriority from LOWEST to LOW for all events. I do not know how the majority of plugins handle priority, but I cannot foresee an issue with this. it would still cancel the event ahead of the default NORMAL priority, and would allow for plugins to execute before GP via the LOWEST priority for mechanics which should override claim protection like my example.

**Comment by RoboMWM** [comment]
Afaik, listening on lowest helps with some anticheat plugins (so players can't use the client-side-placed blocks to tower over a wall for example).

If you don't depend on GP, put GriefPrevention in the `loadbefore` section in your plugin.yml to cancel the event before GP gets to it.


Version 20 will allow you to hook into GP's events (as GP will "funnel" the events and listen to its own events instead of a bazillion other events individually) and cancel as needed.

**Comment by zedwick** [comment]
Ohh, so the server calls the listeners in the order they are registered? That makes sense! Thank you.

**Comment by RoboMWM** [comment]
#63 for following discussion on events in API.

**Comment by blablubbabc** [comment]
I am currently running into the same issue with one of my plugins and try to avoid any plugin-specific hooks/soft dependencies/adaptations.

> Afaik, listening on lowest helps with some anticheat plugins (so players can't use the client-side-placed blocks to tower over a wall for example).

Any source on how exactly this helps? WorldGuard for example listens on normal (and some high) priority as far as I remember.

> If you don't depend on GP, put GriefPrevention in the loadbefore section in your plugin.yml to cancel the event before GP gets to it.

While GP is a popular protection plugin which might justify this, in general there might be lots of other/unknown protection plugins with the same situation. So rather than maintaining a list of protection plugins listening on lowest priority, a more general plugin-unspecific solution would be preferred.
Also this will not work if listeners are dynamically registered/unregistered on config reloads depending on config settings, and also if some "plugin manager" plugin manually reloads a specific plugin.

The more "stable" solution would be for GP to listen on LOW priority and ignore cancelled events, so that other plugins can intercept earlier and cancel the event in specific cases, and by that cause GP to ignore the event.

I will add a loadbefore entry for GP. However, are there any other/concrete reasons for not using a later event priority in GP?

**Comment by RoboMWM** [comment]
What is the issue you're running into? The same as listed in OP?

**Comment by blablubbabc** [comment]
My usecase is with the plugin "Shopkeepers": When players interact with specific mobs (possibly located inside protected claims), I cancel the event and open a trading menu. I am reacting to the corresponding PlayerInteractEntityEvent as early as possible (lowest priority), with the goal that by cancelling it early, other plugins (such as protection plugins) can ignore the event and don't print their 'you cannot interact with that mob'-message.
This seems to match the OP quite well, hence why I commented here rather than creating another ticket.

**Comment by RoboMWM** [comment]
I know sponge has extra event priorities for cases like these.

From an event standpoint, this should happen at `LOWEST` since this event is being blocked as part of a global game mechanic (nothing happens in the claim, nor should any plugins respond as such). The message being printed is an effect that comes along with the mechanic - so the issue isn't so much as the mechanic but that you don't want the message. Tbh, it's almost as if you want to override GP anyways since you're implementing your own protection...

I'll consider using `LOW` priority for GP v20 I guess

**Comment by blablubbabc** [comment]
> I'll consider using LOW priority for GP v20 I guess

Thanks!

**Comment by blablubbabc** [comment]
Sorry for commenting on this old issue, but in case you consider resolving this at some point:
Another alternative to allow other plugins to take over the interaction/protection handling of specific entities without introducing an explicit dependency would be for GP to ignore entities that have a specific metadata key set, like 'GP-ignore', or better a plugin-unspecific key like 'plugin-owned' or similar, that other plugins can set on their custom entities and which would then be ignored by GP. Similarly to Citizens 'NPC' metadata key. It might even make sense to just reuse that metadata key and let GP ignore any entities marked as 'NPC'.
Or even better: Have a configuration setting which allows specifying the metadata keys that should be ignored, so that server owners can configure this depending on the plugins they use (eg. add 'shopkeeper' to the list of ignored entities if they run the Shopkeepers plugin).

This would work for my usecase outlined above, but wouldn't work for the OP's usecase though..

**Comment by zedwick** [comment]
Either idea could be worked to accommodate my use case as well. I would just need to add a little metadata to any item frames when a player puts a book into it.
