### ISSUE TITLE
the spam filter is simply too invasive/restrictive

### ISSUE THREAD

**Issue by rjohnson98126** [GriefPrevention/GriefPrevention#298]
is this a suggestion?  comment?  i dont know, but i've had it with the spam prevention and am just going to disable it for good.   it seems borne of a good idea, but the implementation is overzealous and overly invasive/restrictive, and since there is no resolution in the settings, it's simply a liability.

example 1:  someone logs in, everyone says wb or hi.    The person responding to the hi's and wb's gets their posts soft muted, or possibly a nasty little warning, or even kicked/banned

example 2:  you have quests/npc/citizens type plugin(s).   clicking or entering several menu responses winds up getting that little OMGUSPAM2MUCH warning.

this just winds up offending reasonable players

**Comment by RoboMWM** [comment]
> example 2: you have quests/npc/citizens type plugin(s). clicking or entering several menu responses winds up getting that little OMGUSPAM2MUCH warning.

Said plugin should not be using player#chat, or should be catching and canceling the respective event.

As for the first, usually this isn't an issue, as repeat message detection has been relaxed (at my request years ago). However, I do note that it is imperfect in other areas (both in those doing obvious spam detection avoidance and false positives).

Obviously this'll change or may even be removed and regulated to an addon instead with version 20, especially since the complaints (which compared to others, are quite few relatively) are varied in what the server owners perceive that they need.

**Comment by RoboMWM** [comment]
If you have suggestions of specific changes to make to improve the filter, I'll reopen.

**Comment by rjohnson98126** [comment]
i turned it off long ago, and good riddance.  it was a liability with no actual benefit for my server.    maybe its good for people who run wide open servers that attract every 15 year old with anger management issues? IDK but i agree it's not worth your time to "fix"

 otherwise your plugin is solid and i dont have any complaints, and it's central to my server, so thanks.
