### ISSUE TITLE
Fake glowstone

### ISSUE THREAD

**Issue by matix931** [GriefPrevention/GriefPrevention#3]
Sometimes when you right click some block (place or open) and not protected message appears (ex: "This chest is NOT protected.  Consider using a golden shovel to expand an existing claim or to create a new one."), clicked block become glowstone block.

**Comment by RoboMWM** [comment]
Going to need `/version` and `/version GriefPrevention` and a plugin list/server log might help.

Also, if you can _reliably_ reproduce this on a server with just GriefPrevention as the only plugin, that'd be great.

**Comment by matix931** [comment]
GriefPrevention version: 15.2.2
Server version: CraftBukkit git-Spigot-f9671b8-48b88ed MC 1.10.2 (Spigot 1.10.2-R0.1-SNAPSHOT)

Plugin list:
mcMMO
iConomyRecreation pre-8.0
Jobs3.5.7
Vault
MyHome
PermissionsEx-1.23.4
mcFactiories

There is no error log or other helpful informations in logs

**Comment by RoboMWM** [comment]
Hmm, not sure what mcFactiories does, but I do know mcMMO does attempt to modify chunks. Could you check though if this happens when GP is the only plugin installed though?

I do know that GP does try to show the player's nearby claim when he builds/places/whatever outside his claim, but it wouldn't make sense for it to turn the current block into glowstone (otherwise that'd be inside the claim)

**Comment by erik1988** [comment]
Maybe you are looking at a adminclaim that is 1x1? if you shift-click with a stick in your hand you will be able to see all claims around you.

**Comment by RoboMWM** [comment]
@matix931, can you still reproduce this issue?

**Comment by RoboMWM** [comment]
Closing due to no response. Comment here with a video or image if this is still an issue.
