### ISSUE TITLE
Major Bug Problem 

### ISSUE THREAD

**Issue by DrSnowPengu** [GriefPrevention/GriefPrevention#306]
Hello Author, 

Major Bug Fix Need ASAP: Players can use worldedit to delete players builds even with claim protection on it.

**Comment by bigpresh** [comment]
That's not a bug - Grief Prevention prevents players using normal game mechanics.  WorldEdit is something you'd typically only give to trusted players due to its abuse potential.  GriefPrevention does not claim to prevent WorldEdit.

However, there is a plugin that claims to limit WorldEdit to operating within claims the user has access to: https://dev.bukkit.org/projects/greifprevention-anti-worldedit - I've not used it though.

**Comment by TomLewis** [comment]
Or even better use Fawe! https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/
This has an awesome permissions/settings for all WE things with claims be it WG/Gp whatever.
