### ISSUE TITLE
Bed showing as half when try to destroy it in claimed area

### ISSUE THREAD

**Issue by palipajo** [GriefPrevention/GriefPrevention#315]
www.youtube.com/watch?v=pKQ46dpa_q8

**Comment by Jikoo** [comment]
Those messages and particles are from WorldGuard.

**Comment by RoboMWM** [comment]
I know, you already made a video but it's a lot easier and faster for me to reference and review text than it is to review a video. Please fill out the template next time.

Anyways, Jikoo already told you that's WorldGuard, not GP giving those messages (and thus, the one that's stopping the bed block from being displayed). Likely also a client-side issue, in which case that'd have to be fixed in the client (or workaround in the server), not in a plugin.
