### ISSUE TITLE
players cant use commands on 1.10 version, unless there in there claim

### ISSUE THREAD

**Issue by weltandmelt** [GriefPrevention/GriefPrevention#33]
### What behaviour is expected: Cant use commands

_What you expected to see_ should beable to
### What behaviour is observed: its saying cant use commands because of wilderness administrator

_What you actually saw_
### Steps/models to reproduce:

_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_
### Spigot/Craftbukkit/Paper and GriefPrevention version: using the 1.10 version

**_This can be found by running `/version` and `/version GriefPrevention` on your server.**_
### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```
### GriefPrevention config.yml (if applicable)

``` yml
Paste config inside here
```

**Comment by bigpresh** [comment]
This report doesn't make sense to me.

Please give a better description of what happens, with actual error messages (copy and paste), and the outputs of `/version` and `/version GriefPrevention` from your server.  Are any error messages relating to Grief Prevention logged at startup?

You referred to "because of wilderness administrator" - what is that?  Is that another plugin you have installed?

**Comment by weltandmelt** [comment]
im using griefprevention for minecraft,1.10. (on sponge) and there are no errors popping up  on startup, and /version doesnt work

**Comment by RoboMWM** [comment]
> on sponge

This is a bukkit plugin.

**Comment by weltandmelt** [comment]
can you link me to the sponge tikket then? i cant find it

**Comment by RoboMWM** [comment]
I don't use Sponge, nor am I in contact with any developer who makes the sponge version. Sorry. Try looking where you downloaded the sponge plugin.

**Comment by weltandmelt** [comment]
they dont have one linked, thanks anyway
