### ISSUE TITLE
GP v16.8 / spigot 1.13 - Players can use enchanting tables in someone else's claim

### ISSUE THREAD

**Issue by braceyourself07** [GriefPrevention/GriefPrevention#360]
### What behaviour is observed:
Player can use enchanting table on someone else's claim

### What behaviour is expected:
Since you can't use things like Anvils on someone else's claim, figured it was logical that you couldn't use enchanting tables either.

### Steps/models to reproduce:
Using an enchanting table in a claim where you are not trusted.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Spigot version git-Spigot-fe3ab0d-f41aae4 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
GriefPrevention version v16.8

**Comment by RoboMWM** [comment]
This is expected behavior from what I recall, as these are treated similarly to crafting tables and enderchests. These are unlike anvils which deteriorate on use.

That being said, I'm assuming it's possible to store lapis in enchantment tables? Also Test with 16.9.alpha, see releases tab on main page.

**Comment by Jikoo** [comment]
Inventories are per-player, lapis is not stored.

**Comment by braceyourself07** [comment]
Yep just verified. Welp, self fixing issues are the best! :D Thanks for your attention to this. I'll go ahead and close.  BTW, 16.9.alpha seems to work well so far 👍
