### ISSUE TITLE
Players without existing claims can create 1x1 claims

### ISSUE THREAD

**Issue by masagameplay** [GriefPrevention/GriefPrevention#370]
### What behaviour is observed:
Player without existing claims placed chest next to other player's claim and the plugin generated 1x1 claim for the player without existing claims 
### What behaviour is expected:
There could be some error/warning message to the player without existing claims that there is someone else's claim and cancel claim creation instead of creating that 1x1 claim.
### Steps/models to reproduce:
Player without existing claims places chest next to other player's claim and 1x1 claim will be generated

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Spigot 1.12.2-R0.1-SNAPSHOT
GriefPreventon version 16.8

### Stack trace/error
No errors on in console
```
Paste entire stack trace inside here (don't remove the backticks!)
If not applicable, paste server.log at gist.github.com and paste the link here
```

### GriefPrevention config.yml (if applicable)
```yml
Paste config inside here (don't remove the backticks!)
```

### Plugin list (if applicable):

**Comment by RoboMWM** [comment]
Yea so, not sure about what the best way is to resolve this. I'd like to avoid prompting the user to choose, and I can see this go either way. We should still protect the chest IMO...

The underlying issue here is users understanding the concept of claims, and I really don't know of any other good mechanisms compatible with vanilla survival out there besides what's here.

**Comment by BiGUNMAN** [comment]
I have a few solutions:
1. Allow placing the chest but just don't create a claim? Then when a chest is placed when there is adequate space, land will be claimed?

2. Create the claim, but don't center it around the chest. Make it as centered to the chest as possible without overlapping another players claim? (wouldn't work if there are 2 claims on either side)

Note: Shouldn't 1x1 claims anyways be prevented (If the minimum claim limit is set to 10x10 or whatever the default is?). If not, then maybe have a minimum size for the first auto claim?

Otherwise, combining (1) and (2) will allow the plugin to first try and adjust the claim (and if it isn't possible), it simply waits until a chest is placed in a better position?

**Comment by 112RG** [comment]
I think this should be treated as to close to another player's claim. And that the need chest needs to be placed a distance away described in the minimum claim limit.
