### ISSUE TITLE
Random claimblocks

### ISSUE THREAD

**Issue by Pixiio** [GriefPrevention/GriefPrevention#41]
Still getting reports of players getting random claimblocks. I'll enable debug again.
It looks like they are getting them after restarts. 

^ The plugin does disable properly.
[12:56:33] [Server thread/INFO]: [GriefPrevention] Disabling GriefPrevention v15.3
[12:56:33] [Server thread/INFO]: [GriefPrevention] GriefPrevention disabled.

Edit: So I found the problem. The players that have random claimblocks got random accruedblocks.
Don't really know how that is possible because:

InitialBlocks: 250
Claim Blocks Accrued Per Hour:
  Default: 0
  With 'fasteraccrual' Permission: 110
  With 'fastestaccrual' Permission: 125
Max Accrued Claim Blocks:
  Default: 250
  With 'moreaccrued' Permission: 5000
  With 'mostaccrued' Permission: 10000
AbandonReturnRatio: 1.0

I've set it all to 250 again through SQL but it's still very weird...
Any idea how they are getting them?

**Comment by RoboMWM** [comment]
So, there's a reason why there's an issue template when you create a new issue. I need that plus debug logs, and perhaps your permissions as well.

**Comment by Pixiio** [comment]
Yeah well, I don't have any debug logs right now. I made an ticket issue because you might have said it was something like a setting somewhere.

**Comment by Pixiio** [comment]
Enabled debug. (with the debug jar)
18:12 Looking for expired claims.  Checking data for f4bb9433-50a8-4e0d-8946-b4f6d6812fe8
18:12 <DeletedUsernameForGoogle> has more claimed land than blocks available.  Adding blocks to fix.

It's setting back the accruedblocks again for some players. Probably has to deal something with the thing above?

Also: the only one's with some Griefprevention permissions are the moderators:

```
- griefprevention.claims
- griefprevention.deleteclaims
- griefprevention.ignoreclaims
- griefprevention.restorenature
- griefprevention.commands.deleteclaim
- griefprevention.commands.ignoreclaims
- griefprevention.commands.restorenature
- griefprevention.ignoreclaims
- griefprevention.restorenature
```

**Comment by RoboMWM** [comment]
> has more claimed land than blocks available. Adding blocks to fix.

So, somehow people are claiming more land than is available? Are you dynamically loading/unloading worlds that have claims?

Some of those permissions are given by default to all players (and some of those don't exist, I recommend you get rid of the non-existent permissions).

**Comment by Pixiio** [comment]
Just with /lagg unloadchunks every couple of minutes. But the things is: I think that warn is because I've those players accruedblocks to the default amount (250) for everyone through SQL because they shouldn't have more then 250... But it's still a mystery how they get these accruedblocks.

**Comment by RoboMWM** [comment]
So, I took a quick look over the code when implementing the AccrueClaimBlockEvent, and there are some cases where things could go wrong I suppose. Issue is, in order to best determine where I should even begin testing/debugging, I need more data/a way to reproduce the issue.

That being said, I've already dropped GP's custom accrual and claim block limits. The custom accrual rate can be configured via the AccrueClaimBlockEvent, and bonus blocks are an easy way to "give extra" claim blocks over the limit (they do not count towards the total accrued blocks).

I'll be making the addon as soon as I get time, so if you can find someone who can build an addon to replicate the faster/fastest accrual thing, that'd be great. If not, I may have something ready this weekend, time permitting.

**Comment by Pixiio** [comment]
Thanks for your answer! I think I don't have anymore debug/log data. If you want you could take a look through Teamviewer if you see anything weird. Let me know/.

**Comment by RoboMWM** [comment]
Well, more like any anomalies or patterns you've noticed, i.e. they happen when people first login after being inactive for months/only initially when they login, etc.

The mentioned commit might have something to do with it, since it assumes the player has (practically) no limit if they are somehow offline when we're determining their claim block limit. (I haven't had time to trace all the various ways this code is called.) Since I've now re-instated the singular, global limit, this case should be avoided entirely (and in fact, even with the API available now, an addon could replicate this functionality by "accruing" bonus claim blocks for the player when AccrueClaimBlockEvent is called).

**Comment by Pixiio** [comment]
It looks like they are getting them after a restart. Last time a user was just online, we restarted, and he had so many CB extra.

**Comment by RoboMWM** [comment]
Do you know how much extra? How long were they online? Logs please, if possible!

**Comment by RoboMWM** [comment]
Try 16.4 with https://github.com/TechFortress/GriefPrevention/issues/18#issuecomment-261895573
Comment here if there's still an issue

**Comment by Pixiio** [comment]
It's still there, i'll let you know when I have some more data.

**Comment by RoboMWM** [comment]
With 16.4?

Anyways, try to find out how to reliably reproduce this issue.

**Comment by Pixiio** [comment]
I think the accruedblocks bug is fixed. Still hearing some reports about players getting claimblocks. I'll let you know :)

**Comment by RoboMWM** [comment]
Comment here if this is still an issue. Otherwise I'll assume it isn't given the lack of activity.
