### ISSUE TITLE
Ticking item entities hits timings hard

### ISSUE THREAD

**Issue by ArZorMC** [GriefPrevention/GriefPrevention#424]
### What happened:
 Ticking item entities and doing checks are causing timings to suffer and causing lag

### What you expected:
Minimal effect on timings from grief prevention

### Steps to reproduce:
Specifically, I am using Elite Mobs, and while it has been optimized, Grief Prevention is now producing lag by ticking all the entities Elite Mobs creates.

Any plugin that generates large amounts of item entities would have a repeatable effect.

### Server and GriefPrevention version:
/version: git-Paper-451 (MC: 1.13.2)
/version GriefPrevention: 16.11.5

### Stack trace/error or server log
Timings: https://timings.aikar.co/?id=b1f8715d4b7e4ea48cce62611ccbedc6

### GriefPrevention config.yml
https://hastebin.com/isihozuhel.php

**Comment by RoboMWM** [comment]
I have no idea how you managed to determine GP is the cause of the lag here... nor does GP "tick" entities, or any other plugin for that matter...

**Comment by RoboMWM** [comment]
Also, there's hardly any lag going on in throughout the entire timings here.

**Comment by ArZorMC** [comment]
I have to apologize,  there's a lot i don't know about timing reports still. I saw 200k entites and red text and immediately jumped to "that's bad". Some of my players were complaining about bits of lag so i thought that was the cause.  I remembered talking to the dev of Elite Mobs in the past about some compatibility issues so that's how i jumped to GP again.  Turns out  its all client side and not even as bad as players were making it sound.  Learned a bit more about timings too. Sorry for the novel.

**Comment by RoboMWM** [comment]
That's alright. Was just a little surprised you somehow seemed to be certain GP was the cause. I also talked with magmaguy briefly. But yea, client lag is pretty much the case there, the client will struggle rendering so many entities at once.

Easiest way to determine overall lag is if the green stuff actually drops. Otherwise, orange spikes could indicate areas of lag spikes. Either way, you want to see how much of a tick a particular method takes. If no plugin takes up much when you look at a vanilla method (entityTick and etc.), then it likely is just too much of whatever's there (i.e. entitySheep would mean there's too many sheep on your server as an example).

I think Aikar made a video about reading timings, I'll see if I can dig that up somewhere.
