### ISSUE TITLE
Pets not protected

### ISSUE THREAD

**Issue by StormyIceLeopard** [GriefPrevention/GriefPrevention#432]
I have 4 dogs tamed and sitting. A random player nearly killed one.

Why does this plugin say it offers protection of pets if they can still die?

**Comment by bigpresh** [comment]
Dogs aren't protected, because they attack.  If the plugin prevented people from killing them, then you could have an army of invulnerable dogs who would attack and the victim would be unable to fight back against them.

Keep them indoors inside your protected building and they'll be fine.

I do wonder if a plugin could re-work pet protection in v20, such that dogs are protected as long as they're not targetting the player trying to deal them damage, but if they're targetting you then you can attack them.  Or, maybe, protected while sitting, but not when standing?

**Comment by StormyIceLeopard** [comment]
I like that idea. Protect while sitting or at least while in the claim and sitting.

**Comment by TomLewis** [comment]
I was the one that originally reported the invincible dogs, it truly is terrible on a survival server, just have 20 dogs follow you around your claim and protect you from and PvP, caused a lot of issues and upset player's.
