### ISSUE TITLE
[Request] Vertical subdivision

### ISSUE THREAD

**Issue by Dorito9000** [GriefPrevention/GriefPrevention#433]
I think there should be vertical subdividing in claims. This would be especially useful for things such as towers, where you only want to trust someone on one floor of the tower instead of giving them control of the whole tower.

**Comment by RoboMWM** [comment]
Pretty sure this is a duplicate of some other issue

**Comment by bigpresh** [comment]
Yeah, definitely seen it requested before, and more-or-less noped, for various reasons, including performance (not sure - doesn't seem much harder to check the Y dimension too) and more convincingly confusion in displaying & editing claim heights.

If this *were* ever implemented, I think it should only be subdivisions that can stack - maybe with the corners edited as normal, but with a new command that sets the height of the subdivision you're standing in or something?   I think overall the issue is in displaying & managing such subdivisions in a user-friendly way.

**Comment by RoboMWM** [comment]
Duplicate of #269 and other spigot posts.

**Comment by RoboMWM** [comment]
Duplicate of #269

**Comment by TomLewis** [comment]
We don't need this extra level of confusion, keep gp simple.
