### ISSUE TITLE
[Request] Allow players to access shulker boxes in their inventory while in a claimed area (but not place or destroy boxes in the claim)

### ISSUE THREAD

**Issue by gnubufferoverflows** [GriefPrevention/GriefPrevention#52]
How this would work is when a player places down a shulker box, the place event would be canceled as normal and the shulker box's inventory would be opened up for the player to access. The player would not be able to open up the claim owner's shulker boxes, nor destroy them. Also, in areas where the player can build (such as in Wilderness), the player would still have to place his/her shulker boxes to open them.

Why? When Mojang created shulker boxes, I doubt they thought about them being used on a server with plugins where you can't place them wherever you want, and this feature couldn't be exploited to make changes to claims. **It would just open the shulker box's inventory when someone tries to place one and not allow the place to happen as usual, except that the "You don't have permission." message would be omitted.**

Anyways, would like feedback on this idea from y'all before I take the time to make a PR, or if someone else wants to that's cool too.

**Comment by RoboMWM** [comment]
Considering how this does diverge from vanilla behavior (since there is no shulker box that can be physically broken, for example), and requires plugin-side inventory syncing/changing/whatever trickery, this type of behavior would be best suited in an addon rather than having to be maintained within the plugin - especially considering it has to alter NBT and such (which may require NMS access?)

**Comment by Jikoo** [comment]
I believe it's possible via the API by manipulating the BlockStateMeta of the shulker box, but yeah, there's a lot of inventory trickery.

**Comment by bigpresh** [comment]
I think I'd agree that the divergence from vanilla behaviour would be a bit too big of a change, and the trickery involved might be a bit fragile - and the slightest little bug that causes players to lose items would cause a lot of complaining!

It'd also be different from how ender chests have always worked - you have to be able to place them down to access them, and that's fine, so why should shulker boxes be handled differently?  (Admittedly, the latter "contains" the contents, rather than just accessing them, so it's as though you're actually carrying the items with you - but the point still applies, I think.)

**Comment by RoboMWM** [comment]
Yea, was also going to add the argument about ender chests. Thanks for doing that for me :)

**Comment by BillyGalbreath** [comment]
This isn't a GriefPrevention addon, but it does what you want

http://ci.dwdg.net/view/Pl3x/job/BetterShulkerbox/

**Comment by Jikoo** [comment]
@BillyGalbreath Haven't tested the plugin myself, but doesn't your lack of handling moving/dropping the box in hand allow duplicating any contained items? I'd probably just cancel click and close if the box isn't found but it's still open, dunno what's best. May also want to close if a PlayerItemHeldEvent/PlayerSwapHandItemsEvent is fired, is possible to do even with a vanilla client if you're lagging. Hold 2 shulker boxes, attempt to open 1, change to the other before client gets informed of the window opening. Dupe all items in first box, profit.

**Comment by BillyGalbreath** [comment]
I havent tested it much @Jikoo but you do raise some good concerns. I'll test more and fix any exploits it may cause and report back.

Edit: Your concerns were indeed correct. I was able to exploit it in many ways. I will be working on fixing the plugin, and i'm going to talk to md_5 to see if he cant fix the original problem with shulker boxes a better way. If not I'll see if paper cant get his commit reverted and fixed properly. https://hub.spigotmc.org/jira/browse/SPIGOT-2997

**Comment by Jikoo** [comment]
Ended up making my own version of the same concept, [PortableShulkerBox](https://github.com/Jikoo/PortableShulkerBox/releases). Just a simple right click air, no claim stuff, requires the permission `portableshulkerbox.open` to use. Java 8 required, no config or commands.

As far as I know there are no dupe bugs, tried my best to break it. You'll get a warning in console if something does go wrong, includes the player's name.

**Comment by Jikoo** [comment]
Since there are now multiple plugins that allow you to open shulker boxes without placing them (give it a quick search - I'd say of the 2 here mine's probably better due to certain issue prevention systems, but there are far cooler and more user-friendly alternatives out there) I'd say this has been solved - the original request is fulfilled without giving an unfair advantage to users in claims where they can't build.

**Comment by RoboMWM** [comment]
Idk, it's still a valid addon request.

**Comment by RoboMWM** [comment]
oh nvm, he's asking for backpack functionality, read a little too fast.
