### ISSUE TITLE
Allow non trusted to access lecterns to read books

### ISSUE THREAD

**Issue by MNGOwO** [GriefPrevention/GriefPrevention#537]
I think the ability to leave Lecterns open so people can read books you place down for quests or adventure stuff would be really useful. Currently they are fully protected and therefore only people who are trusted can read within

**Comment by Ashurit** [comment]
Hello, in addition to this suggestion,
It could be nice to add variant situations following trust type you have in the claim :

"not trusted" : none access to the lectern but read the book.
"containerTrusted" : Access to book reading and also book changing (remove and place a book on the lectern) but impossible to break the lectern.
"Trusted" : Access to book reading / changing and break the lectern.

[Obviously if you don't want to apply this on all the claim where the lectern is while you want to apply it only on the concerned lectern, you just have to use sub-claim to define a specific access on the lectern spot.]

Regards.

**Comment by Jikoo** [comment]
Container/full trust should already function as you described, the lectern is treated the same way as other blocks with an inventory.

**Comment by krlsmnk** [comment]
I agree. My server and I discovered this one today. Non trusted users should, in our opinion, be allowed to read, but not remove, the book. 

Could pose problems for contraptions using them, though. Unsure how to resolve that one.

**Comment by AntZaro** [comment]
We just ran into this issue while getting our server ready for a 1.14.4 update. We agree something needs to be changed but this is our opinion: 

non-trusted: should remain as is, no access at all
access trusted: ability to read the book
container trusted: (same as now) read the book and remove it/ replace it
full trust: (same as now) read, replace, destroy entire lectern  

I think this just adds another layer of customization to make it so everyone is able to secure it in the way they want.

**Comment by RoboMWM** [comment]
As an fyi I haven't had time to mess around with 1.14 yet; are the methods to remove/place the book similar to reading the book (i.e., I'm assuming this is something you can do within the inventory menu)?

(Yes I could wiki this (maybe, if it has all actions described, and I can guess at the events called) but I'm fixing other issues atm, and don't want to miss anything that could be overlooked - I rather err on the side of overprotection rather than special-cased underprotection.)

**Comment by AntZaro** [comment]
I don't think I know enough technical stuff to answer your question. But does it help if I tell you that we were able to achieve the desired behaviour using WorldGuard?

In other words, we were able to use WorldGuard to make it so players can read a book but not remove it. We're using the most recent official release of WorldGuard.

**Comment by RoboMWM** [comment]
How did you use worldguard to accomplish this?

**Comment by AntZaro** [comment]
It was actually one of my Admins who did it. But he said that WorldGuard has the flags “chest-access” and “interact” similar to container trust and access trust respectively. Basically, he just made a subregion that made it so they couldn’t access chests (containers) but they could interact with them (open enchantment tables, lecterns, etc) without removing the item because they couldn’t actually access the chest container.

Does that make sense?

**Comment by ShaneBeee** [comment]
Im not sure when added, but spigot has a [**PlayerTakeLecternBookEvent**](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerTakeLecternBookEvent.html) ... that being said, if its an inventory event that prevents from "seeing" the book, you could un-cancel that for all players, and then if they attempt to take the book, use the Bookevent and cancel that. 

In my opinion, all players, regardless of claim perms, should be allowed to read a book. If you dont want all players to read a book, put it in a room they dont have access to.

**Comment by RoboMWM** [comment]
> In my option, all players, regardless of claim perms, should be allowed to read a book. If you dont want all players to read a book, put it in a room they dont have access to.

*opinion

IMO it should follow /accesstrust, or an option for it perhaps. This mechanic is fairly new to Minecraft (information that pops up a "UI" vs. from an item; public info has been otherwise showcased on a block such as a sign or item frame), but considering it does require interaction unlike viewing info on signs or item frames, I think it should be part of /accesstrust. But I see the argument for both... hmmm.

**Comment by ShaneBeee** [comment]
> *opinion

OOPS, that's embarrassing!

The reason I stated it should be open to everyone is, its just a book you can read. You can't really "take" anything or gain anything from reading it.

Me personally, if I wanted everyone to read my book, I would put the lectern in a place anyone could read it. If I wanted it to be private, I would put it in a room with a gate/iron door, something that requires access trust to get into the room. 

Thats just my opinion though.

**Comment by RoboMWM** [comment]
Yea, I see a case for both, especially since this is a new mechanic, there really isn't any prior behavior to be "consistent" to. I guess we're trailblazing the standard here.

**Comment by ShaneBeee** [comment]
> Yea, I see a case for both, especially since this is a new mechanic, there really isn't any prior behavior to be "consistent" to. I guess we're trailblazing the standard here.

For the PR, to make this go both ways, should I make a config option, something like "Lecterns-Require-AccessTrust" and if yes, which would you prefer as default, true or false?

**Comment by RoboMWM** [comment]
make it similar to the option for villager trading

**Comment by ShaneBeee** [comment]
> make it similar to the option for villager trading

I ended up doing this (Seems pretty darn close to the villager one)
```yaml
    VillagerTradingRequiresPermission: true
    LecternReadingRequiresAccessTrust: true
```

**Comment by zedwick** [comment]
Bit of a coincidence two of us created a fix for this the same day.

Should definitely require access trust as turning the page in a lecturn can alter redstone comparator output.

**Comment by RoboMWM** [comment]
Thank you for that info zedwick. Agreed as well.
 Unless yours is vastly different, would you mind fixing/reviewing shanebee's PR?
