### ISSUE TITLE
 players can break blocks in unclaimed places

### ISSUE THREAD

**Issue by llronaldoll** [GriefPrevention/GriefPrevention#539]
### What happened:
_What you saw_

I wish players could not build or destroy blocks in unclaimed areas, but new players can destroy and build in any place not claimed, can anyone help?
### What you expected:
_What you expected to see_

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`:

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

**Comment by bigpresh** [comment]
If you want players to not be able to break blocks outside of claims (i.e. in the wilderness) then OTTOMH, you need to change your config under claims.mode from Survival to SurvivalRequiringClaims.

Since you didn't bother to fill out the issue template, I can't see what your current config is or whether you've tried that.

However, I'm not sure if that's what you want, because you said:

> I wish players could not build or destroy blocks in unclaimed areas, but new players can destroy and build in any place not claimed, can anyone help?

... so you don't want players to be able to build/break blocks in unclaimed areas, but you *do* want new players to be able to?  i.e some kind of "if you're under $x minutes play time you can break blocks in the wild, otherwise you can't"?  If that's what you mean, then no, GP itself can't do that (but an addon could do).   If that's *not* what you mean, please explain in a little more detail, as I may be mis-understanding you.

**Comment by llronaldoll** [comment]
Okay, I understand, can you tell me how I can only admins be able to claim blocks in one world?

**Comment by RoboMWM** [comment]
> you need to change your config under claims.mode from Survival to SurvivalRequiringClaims.
