### ISSUE TITLE
Investigate different methods of storing config key/value pairs.

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#571]
**As a** developer,
**I want** an efficient way to define config keys and default values
**So that** I can easily add config keys and know their type when referencing them throughout the codebase/in addons

# Criteria
- Defining a new config key and default value requires only editing a single section of a single class
- Config values can be easily populated from a file (e.g. iteratable)
- Config keys are defined at compile time and are able to be referenced in the codebase (e.g. via autocomplete)
- Config value calls return the appropriate type at compile time (i.e. does not require casting!)

### Bonus criteria
- Config value is immutable
- Only have to edit/add a single line

## Tried
- Enum with `Object` as value
  - type is not known at compile time
- Enum for each type
  - config options grouped by type instead of component
  - no method sharing/reuse (enums in Java cannot extend classes)
- public static variables
  - mutable
  - requires reflection to iterate
- public methods
  - every call will cause a default value to be instantiated
    - May be minor and a non-issue issue though, as these are primarily primitive types or small strings.

## Currently trying out

- Generics 9f2c2e4fcf72aed75e019177260f9b9129a69b4f

**Comment by RoboMWM** [comment]
@Jikoo thoughts? Wondering if others have come up with better config solutions.

**Comment by Jikoo** [comment]
My best effort was a system that implemented autosaving defaults.
Essentially, I internally had a Map storing all my key-value pairs. This map was populated from the existing config. There were no methods to get a value without a default. If the value was not present (allowing present and null, exclusively not present) the default was inserted into the map. The config was flagged dirty, and in a sync task (to prevent multi-checking methods causing repeated excessive file writes) it was saved. This system allowed me to create an Enum storing key-default pairs, which could then be used to fetch values that did not exist. Data types were a bit hairy, but I believe that could have been solved with a bit more work on generics dependent on the default's type.

I ended up dropping it because I kept running into "issues" with the design, flaws where people electing to behave stupidly could break my design. I think I could do better now, but honestly these days I mostly prefer Bukkit's Configuration API. Small scale, I'm just there for a quick and dirty solution. Mid-sized projects, each section is granted its own ConfigurationSection to treat as its config.

**Comment by RoboMWM** [comment]
Now trying out generics. Might go with this. Loading will be interesting, may have to do something similar to YamlConfiguration regarding numbers. 9f2c2e4fcf72aed75e019177260f9b9129a69b4f

**Comment by RoboMWM** [comment]
Went with using generics. Classes are in the `config` package.

I think I went with some sort of pseudo "factory" approach. Idk because I've never made "Factories" in OOP before. But this satisfies my criteria:
- Defining a new config node only requires adding a single line of code
- Config node key name and value type is defined at compile - it shows up in the IDE
- Config nodes are immutable
- ConfigNode is loaded from (and can update) an existing config file
