### ISSUE TITLE
Disable Setting off a Raid in a Claim the Player Isn't Trusted In

### ISSUE THREAD

**Issue by Wpgradford** [GriefPrevention/GriefPrevention#575]
**AS** a player
**I WANT** a permission/restriction that prevents players who aren't trusted in a certain village to set off a raid in said village. I realize this would probably be a difficult thing to add, because raids are set off by a status effect and only within the boundaries of a village, but I feel in 1.14 it's a much needed addition.
**SO THAT** players can't set off raids in villages that don't have them trusted. As it stands right now, a random player that isn't even affiliated with the village can run through and start a raid. These can be very irritating to deal with, and it only makes sense to disable them on claimed land. Thanks for hearing me out!

**Comment by ShaneBeee** [comment]
1) I see that Robo marked this as "Add-on suggestion", in my opinion this should be part of GP itself, because a person could use this to grief other villages. 
ex: Im a jerk, and I notice I have "bad omen" so I find a player I dislike, and enter their claim/village, which then therefor starts a raid. The raiders would then attack this player's villagers, and a ravager could destroy crops/trees.

2) Currently Spigot has no API for raids. Theres no events or anything that would fire when a raid is triggered, so in Spigot's current state, this would be quite hard (if not impossible) to implement. 

Someone did create an issue on [**Spigot's Jira**](https://hub.spigotmc.org/jira/browse/SPIGOT-5211), requesting the addition of some raid based events. I recommend voting on this, to help get these much needed events added to the API

**Comment by Jikoo** [comment]
I understand why you'd consider triggering a raid to be a potential act of grief, but I don't believe it belongs in the main plugin. Where does GP draw the line? Players have a responsibility to build with some semblance of intelligence. If your village is not built to protect villagers properly, a regular raiding party or a zombie can wipe it entirely. You can quite easily lose an entire village to normal game mechanics without external assistance. I don't think it's GP's responsibility to prevent a player-triggered mechanic that essentially only exacerbates existing risks. The only thing that cannot occur without raids is ravagers, and preventing ravager damage was introduced as a config option in cdeac806.

It does sound like a nice feature, but only because continuous raids get annoying, not because of any particular risk.

**Comment by ShaneBeee** [comment]
You raise a very good point, I never thought of it that way.

**Comment by Wpgradford** [comment]
I agree with both of you, although to some extent. I believe that raids are comparable to spawning a wither. Now, if a player were to spawn a wither outside of another player's base, would it be within GriefPrevention's bounds to prevent said wither from damaging passive mobs inside the claim? I think it would be. Admittedly, I have withers disabled on my server, so I'm not sure how GriefPrevention handles them. I think the plugin should treat raids the same way as wither attacks, possibly by preventing pillagers and other raiding mobs (excluding zombies) from damaging villagers inside of claims.
I do believe some of this is up to players simply protecting their villages, but I think there is an extent to where it would be optimal for GriefPrevention to handle it. After all, a few features of the plugin would be unnecessary if considered with the "player can prevent it, why should GP deal with it?" point of view. You both bring up good points.

**Comment by ShaneBeee** [comment]
You also raise a good point.

Going back to what Jikoo said, I thought about it more. Yes you are correct, zombie attacks can kill villages, but for the most part, a random player cant initiate this, but a random player CAN initiate a raid on a village, which would be considered grief.

If **I** were to be in my village with Bad Omen, and the raid started, then yep, that is my own fault and that should be allowed. But if other players are getting bad omen then wandering into claims they do not have perms for, that's very unfair to the claim/village owner.

Yes, I do agree that its the owners job to protect their claim, ie: fences/walls/etc, but at the same time its very easy to NOT get bad omen & have a raid start, so if someone where to come into my village with bad omen and start a raid, I would consider that grief. 


As stated, Spigot currently does not have an API for anything to do with raids. If/When they do add that API, if Robo doesn't feel like adding this to GP I'll add it to GP-Flags
