### ISSUE TITLE
Plugin should remember if the user is ignoring claims or not

### ISSUE THREAD

**Issue by JasonHorkles** [GriefPrevention/GriefPrevention#586]
**AS** an owner
**I WANT** the plugin to remember if the user is ignoring claims or not
**BECAUSE** it's annoying to type /ignoreclaims every time I rejoin the server

**Comment by bigpresh** [comment]
Personally, as a responsible owner/admin, I *like* that it doesn't; I do *not* want ignoring claims to be my default, I want it to be a special thing I have to invoke specifically only if/when there's a very good reason to do so, and to turn back off ASAP.

I suppose GP could have an additional permission for e.g. AlwaysIgnoreClaims which could be granted to any user who should always have ignoreclaims in effect, so GP doesn't actually need to do any remembering, the permissions system you're using can handle it - that would I assume do what you want, but I do, personally, think that that's the wrong way to run a server.

**Comment by JasonHorkles** [comment]
Yeah a permission could work as well. Right now it's useful because I can see how much stuff people have from/for the shop so I can balance the prices easier. It's kinda hard to know what your prices should be if you can't see any stats.

**Comment by bigpresh** [comment]
Depending on how this shop works, could you not just grant yourself container trust on whatever claim it's in?  (I'm assuming you are using ignore claims to be able to look in some chests/hoppers/dispensers/whatever hooked up to some kind of shop mechanic?)

**Comment by JasonHorkles** [comment]
I have an EssentialsX sign shop warp and so I want to kinda see who's buying what and how many so I can keep the prices balanced. For example I thought it was harder to earn money than I thought because when I looked in someone's chest they had a whole farm going so I adjusted certain prices in the shop accordingly.

**Comment by RoboMWM** [comment]
This has been discussed before, can't seem to recall where though... am trying to find it.

It sounds like the reason you want this feature has something to do with EssX signs and shops though. Idk why you'd need permission to interact with signs, but if the issue is chests, you may want to consider a plugin that's compatible with region protection plugins like [PrettySimpleShop](https://dev.bukkit.org/projects/prettysimpleshop)

**Comment by JasonHorkles** [comment]
I use worldguard for stuff like the shop. The shop really has nothing to do with this issue though, it's just because bigpresh asked *why* I wanted it always on

**Comment by RoboMWM** [comment]
> it's just because bigpresh asked why I wanted it always on

Well, that does relate to this feature request. Features aren't implemented for no reason.

**Comment by JasonHorkles** [comment]
Ok but if the feature isn't added then whatever, I can just use skript to make me do the command every time I join the server it's no big deal

**Comment by RoboMWM** [comment]
Yea, I'd suggest doing that. The reason why this isn't a persistent toggle follows along with the principle of granting administrative privileges only when necessary. This helps prevent accidental administrative actions being taken. If it's affecting normal operation then the design should be reworked.

It's somewhat mentioned in https://github.com/TechFortress/GriefPrevention/issues/561#issuecomment-511932061 but I know there was something more in-depth elsewhere... just can't find it.

**Comment by Jikoo** [comment]
I feel like bigpresh summed up my feelings on it well. If a permission is added, I do hope that it defaults false and has no parents. There's no guarding against careless admins with permissions plugins that support wildcards, but may as well take as many steps as possible to prevent it.

Forgive me for my blunt opinion, but to me wanting GP's full power constantly indicates either a poorly designed system or a bad balance between fun and administrative duties. How much time do you take to actually play the game? GP in its current state is aimed at responsible admin behavior when necessary while allowing normal gameplay, not an always-on admin who treats their server like a job.

**Comment by JasonHorkles** [comment]
Alright fine you have your way, I'll have mine.

**Comment by Jikoo** [comment]
I don't mean to offend, I'm actually wondering. Text doesn't convey that well, and I can't ask you to read a 10 paragraph essay where I harp on the finer points.

Is it server design or is it just your administrative style? Mostly concerned because most people who take the always-on route end up having an angry burnout. What I was trying to say is that while making GP allow you to just constantly stay in admin mode may be an easy solution, if you are having to put in a lot of manual effort you should likely seek to reduce the workload, not necessarily just streamline the process of working.

If your majority workload requiring admin access is trying to balance shops against supply/demand, I know at least one plugin that automatically does that for you, [AutoPrice](https://dev.bukkit.org/projects/autoprice). Doesn't have sign shops, but I'm sure there are other similar plugins out there.

**Comment by JasonHorkles** [comment]
Probably both. I have hardly any staff right now so it's basically all just me building the server lol

**Comment by JasonHorkles** [comment]
Also yeah it might as well be my job because I have nothing else to do till school starts really
Not that I'm making any profit off of the server though

**Comment by JasonHorkles** [comment]
Oh and thanks for the auto plugin suggestion but it appears to be old and for 1.7 so I'm afraid I can't use it even if I wanted to
