### ISSUE TITLE
Claims inside anothers. Question-FeatureRequest

### ISSUE THREAD

**Issue by Emivg** [GriefPrevention/GriefPrevention#596]
**AS** Server admin
**I WANT** a feature/dont know if its possible with another plugin or this main one
**BECAUSE** It could be really good for my server (city-survival)

The idea: Possibility to claim a big admin land and have small ones inside of it. This is really good for cities and big towns (to protect the roads so people cant grief them)

Representation (important to read the texts to understand it): http://prntscr.com/owltoc

Regards!

**Comment by bigpresh** [comment]
A partial solution is to create sub claims within the main claim (using the subdivideclaims mode), and then give the "owner" of that subclaim the appropriate trust on the subclaim.  It's not perfect, though, as the claim wouldn't show as theirs, and they wouldn't be able to give trust to others, I'm pretty sure, as I don't think permissions trust applies to sub claims - but I may be remembering that wrongly?

It would be nice if subclaims could have their own owner, but it could possibly cause confusion - "it's my claim, why was <other player> able to delete it / untrust me / whatever?!" - well, because they own the parent claim.  I can see that possibly causing friction.

**Comment by RoboMWM** [comment]
You're basically describing subclaims, an already-implemented feature (albeit in a very hard-coded and nearly unmaintainable way).
