### ISSUE TITLE
Request ability to claim regions that have Y limits (top-bottom) via /pos1 /pos2 method

### ISSUE THREAD

**Issue by gmalone** [GriefPrevention/GriefPrevention#629]
**As** an admin/world designer
**I want** to define GP regions using /pos1 and /pos2 WorldEdit style
**Because** Minecraft worlds are comprised of regions above and below each other and need their own properties

This request is related to the following existing Issue, but more specific:
https://github.com/TechFortress/GriefPrevention/issues/561

In a vertically stratified world design -- e.g. a village below and an overarching base above, or, a forest below with a hovering game platform space above it -- there is need to define those vertical regions separately and give each their own protection and other properties.

Would you kindly consider enabling the defining of GP regions in the same/similar way a WorldGuard/WorldEdit region is define using /pos1 /pos2 method?

Thanks.

**Comment by TomLewis** [comment]
Then use world guard

**Comment by RoboMWM** [comment]
This is a huge feature request, as the design only considers 2D areas instead of 3D volumes (with exception of the lower y value - but no claims can overlap so it's still considered part of the claim).

While the request for the WorldEdit-esque selection is similar to the issue you linked, it really isn't all that different than what you do with GP normally. The 3D claims is far more similar to #269 (without subdivisions), and so will close in favor of that.

**Comment by RoboMWM** [comment]
Duplicate of #269

**Comment by gmalone** [comment]
I hadn't seen #269.  Sorry for duplicating the request.

As far as "use WorldGuard" goes, I will and am.  Just thought it'd be great to be able to have one less plugin (WorldGuard) handling region protections.  Combined with the plugin GriefPrevention Flags, GP becomes quite the unified protection package rivaling WorldGuard.  Until I learned it can't be done.  Thanks for your time.

**Comment by RoboMWM** [comment]
GP's design is player-oriented, so it will opt to be simpler instead of WorldGuard, which is heavily admin-oriented.
