### ISSUE TITLE
players can kill mobs inside claim

### ISSUE THREAD

**Issue by ABKgamer** [GriefPrevention/GriefPrevention#645]
players can kill hostile mobs inside claim. so we can use hostile mobs for farms and display. maybe at least named mobs can be protected by claims

**Comment by RoboMWM** [comment]
Ya this is intended, hostile mobs actively target and damage players - players need to be able to defend themselves.

I suggest encasing the mobs in fence/glass like my players do.

**Comment by ABKgamer** [comment]
i can cover them but iron farm will not work

**Comment by Jikoo** [comment]
I've created [GPExtraProtections](https://github.com/GPAddons/GPExtraProtections) which adds this feature.

**Comment by RoboMWM** [comment]
o dang stole the logo and all :c lol it's k, I just wish the guy who "owns" the org with the same name as the plugin would not mislead people into thinking this plugin is dead.

I'm thinking of making some "official" addons as the "v20" plans come to fruition such as "simple subclaims" and the like since players on my server do use subclaims quite a bit despite me not advertising that feature at all (going so far as to mute it from the messages.yml).

**Comment by Jikoo** [comment]
I'll happily pass org ownership to you tbh, I just didn't want a bunch of addons hard linked to my account if I end up being the one to port Siege or something - that's really not something I want to maintain, but I'd be willing to migrate it.
