### ISSUE TITLE
Players are able to jump on ticking blocks

### ISSUE THREAD

**Issue by Scarecrow-01** [GriefPrevention/GriefPrevention#651]
### What happened:
I have recorded proof of players abusing a glitch that lets them jump on blocks they place in claims right before they disappear (a matter of milliseconds) letting them climb walls relatively easely.
 
### What you expected:
I'd like to see this bug fixed in 1.14.4.. People are unable to do so in 1.13- servers

### Steps to reproduce:
Just place a block below you while jumping and, after some practice, you'll be able to reproduce this.
1. Go near the wall you want to climb
2. place a block below you on the wall
3. jump at the right time
4. get into other people bases like a sneaky motherf****

### Server and GriefPrevention version:
Spigot 1.14.4
GriefPrevention: 16.12.0

**Comment by RoboMWM** [comment]
This is the responsibility of an anticheat plugin. GP cancels the block placement server-side. The client will place the block though, and only will verify with the server afterwards - so this is a client-side issue. NCP successfully stops this by detecting it as cheating since it never believes any block was placed in the first place so it thinks the player is attempting to fly - and appropriately cancels the action.
