### ISSUE TITLE
Claims not expiring according to the config settings

### ISSUE THREAD

**Issue by Weasel-Beans** [GriefPrevention/GriefPrevention#654]
I've been using the settings in the config to automatically remove claims after a certain amount of time, unless the owner has 10,000 accrued claim-blocks and/or 10,000 bonus claim-blocks. Recently I've been notified of multiple claims that are well past the 30 days mark from players who have far below the amount of claim-blocks required to keep their claims.

Here's the config: https://pastebin.com/CK9LfN6c

Here's a timings report: https://timings.aikar.co/?id=d61b23b518574a109121714a5fe0e1f1

**Comment by Jikoo** [comment]
Claim expiration iterates slowly through players, meaning it may take some time for servers with a lot of players to actually hit the ones that need their claims expired.
From your timings report, it did successfully find 3 players to expire. Since the task locating unused claims doesn't appear in the timings at all, I suggest reducing `GriefPrevention.Advanced.ClaimExpirationCheckRate` (seconds per player checked) if your server has a larger player base.


Unrelated: Please update OpenInv. You're four versions behind, one of which includes a fix for an edge case dupe bug.

**Comment by Weasel-Beans** [comment]
That makes sense, I'll lower that setting to 20.

Thanks for the heads up on OpenInv! I'll update that now too.
