### ISSUE TITLE
PlayerInteractEvent error

### ISSUE THREAD

**Issue by 8qBITs** [GriefPrevention/GriefPrevention#692]
### What happened:
Error spamming on  PlayerInteractionEvent

### What you expected:
No errors

### Steps to reproduce:
No idea, i am using forge bukkit 1.12.2 and this error keeps poping up altho plugin works fine.

### Server and GriefPrevention version:
16.8 1.12
### Stack trace/error or server log

https://gist.github.com/8qBITs/ff5bc46350f925fecffb45245f219112

### Plugin list (if applicable):
vault

**Comment by RoboMWM** [comment]
Forge bukkit?

**Comment by 8qBITs** [comment]
Aka LavaPowered/Spigot with forge

**Comment by RoboMWM** [comment]
Looks like Paper. Anyways, the issue is with whatever this frankenstein of a server mod you're running.

Block is determined not to be null:

https://github.com/TechFortress/GriefPrevention/blob/05497b7b6a2b693302c41a79c98ff60c3757837e/src/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L1602-L1604

But the type of the block (assigned as `cacheKey`) is somehow null

https://github.com/TechFortress/GriefPrevention/blob/05497b7b6a2b693302c41a79c98ff60c3757837e/src/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L2498-L2502

Gonna guess someone is right-clicking a non-vanilla block.
