### ISSUE TITLE
Notify players when they enter a claim

### ISSUE THREAD

**Issue by gjvnq** [GriefPrevention/GriefPrevention#693]
**As** a player and an admin
**I want** to have a config option to notify players when they enter claimed areas.
**Because** I want better usability.

It can be either a chat notification like Towny or a title text like PlotSquared.

**Comment by bigpresh** [comment]
I would have sworn I'd responded to this ticket already (maybe a similar one?) but found it while looking for something else.

Definitely could be done by an addon, but I think it could be a quite expensive check - firing claim lookups on each movement event would soon cause excessive load.  Smart design e.g. caching the last location, and only calling GP's API to check for a claim at the location if the player's location was last checked longer than a certain threshold ago and/or their location is further than $threshold_blocks from the last cached location could help manage that - or maybe just firing a check for all players every couple of seconds or something rather than listening for movement events.

I think it could still have a performance impact, though, and I certainly don't think it's something that should be done in GP's core.

I'm also not that sure of the value, I would see that as likely to be pointlessly annoying when walking around, and if you're interested in a particular area (either to see whose it is, or whether it's claimed) you only need click with a stick.

**Comment by RoboMWM** [comment]
It's already been done a few years ago in an addon, GriefPrevention Flags.

**Comment by bigpresh** [comment]
Cool, that sounds like a "close this issue" to me then :)
