### ISSUE TITLE
Breaking a block through a stairs hole protects it

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#776]
### What happened:
Video
https://www.youtube.com/watch?v=LaRQ8ydzbxg

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Spigot 1.12.2
Paste of `/version GriefPrevention`: 16.8

Yes I know I'm using 1.12.2, yes I know its not supported.

Very weird bug here, that i'm assuming is GriefPrevention as I cant think of anything else it would be protecting the block, there's no error message to figure it out.
This is merely in a players claim they have trust in, is it possible when the player trys to break a block through the hole in stairs GriefPrevention could be blocking it?

**Comment by bigpresh** [comment]
I don't *think* GP does anything that cares about visibility or *how* you're trying to break a block, just whether you're allowed to break a block in that position.

That sounds much more like an anti-cheat plugin failing a visibility check - i.e. thinking that you shouldn't be able to break that block because you can't see/reach it because another block is in the way.

(EDIT: you omitted the list of plugins requested in the issue template so I can't see if you are using an anti-cheat plugin (e.g. NoCheatPlus or similar) but that's certainly what it sounds like to me.

**Comment by TomLewis** [comment]
I use matrix, visibility check, I can disable that in game and test it easy enough! Let me give that a try

**Comment by RoboMWM** [comment]
Yup, that's anticheat.
