### ISSUE TITLE
Unsaddled animals do not take environmental damage outside claims

### ISSUE THREAD

**Issue by zhro** [GriefPrevention/GriefPrevention#79]
Unsaddled animals such as horses and llamas do not take environmental damage outside of claims. This creates immortal entities.

Tamed llamas AND horses appear immune to: lava, fire, tnt, suffocation.
Tamed horses are immune to drowning but NOT llamas.

I can understand if this is a feature on claims but not off of them.

**Comment by RoboMWM** [comment]
If I recall correctly: Yes, this is a feature which idk if it's disable-able in the config (I think it is, can't recall) since Big_Scary had issues with wolves teleporting into blocks and suffocating. I'm in the process of refactoring this project and will likely be removing this (an addon can re-add it).

**Comment by RoboMWM** [comment]
Btw. what's your config? This may relate to PvP settings.

**Comment by RoboMWM** [comment]
Related to #213, and I'm going to assume that saddled or not doesn't matter...
