### ISSUE TITLE
[BUG] Certain things are not properly protected

### ISSUE THREAD

**Issue by ShaunDreclin** [GriefPrevention/GriefPrevention#80]
So far I've noticed three things that GP doesn't work on. (Direwolf20 Modpack)

Double doors - When you try to open protected double doors, GP tries to "close" them again but always leaves one open and available to walk through.

(RFTools) Screen - Protected screens give the message that you don't have permission to use them, but you can still freely click on buttons on them to control other people's systems.

(ExtraUtils2) Golden lasso - Mobs standing in protected land can be snatched by golden (and presumably cursed) lassos.

**Comment by RoboMWM** [comment]
The template is there for a reason. Regardless, GP is a bukkit plugin. Mods need to fire bukkit events in order for their actions to be canceled. You can try adding them to the config.

**Comment by ShaunDreclin** [comment]
Double doors are vanilla though. Could at least look into that one

**Comment by bigpresh** [comment]
> Double doors are vanilla though. Could at least look into that one

Can you be more specific in exactly what happens?  I use double doors and have no problems.  At the end of the day, there's no such thing as "double doors", really - it's just a pair of single doors next to each other (I assume that's what you mean?) - so attempting to open either of them is just the same as opening a standalone single door.

Do you, perhaps, have some kind of plugin installed which makes two doors next to each other open together?  (e.g. SyncDoors, BetterDoors etc) - if so, there's you problem - GP can't block non-vanilla actions unless the other plugin knows how to fire GP events etc.

**Comment by ShaunDreclin** [comment]
Hmm maybe it's not vanilla then, I thought it was. Yes two doors placed next to each other both open together as one.

**Comment by bigpresh** [comment]
Yeah, doors opening together is not vanilla behaviour (well, unless they're both being triggered by a bit of crafty redstonery, but when opened by the player, only the one clicked will open).

That's why the default template on raising an issue asks for a list of plugins, for what it's worth - so we can identify other plugins that could be interfering or adding non-vanilla behaviour that GP doesn't know about.

You did mention you're using Direwolf20's modpack, and having had a quick glance at that, I don't see any mod whose name directly suggests it's responsible for that behaviour, but there's quite a few mods in it!

Anyway, GP will only be seeing the interaction event for the door clicked, and will correctly block it; whatever plugin is also catching it and opening the adjacent door would, I imagine, need to listen at a lower priority and check if GP has cancelled the event by the time it sees it, or be written to integrate properly with GP - either way, that's one for the developer of the plugin in question.  If you can work out which one it is and remove it or disable that feature if it's part of a larger plugin, that might be your easiest fix :)

**Comment by ShaunDreclin** [comment]
For anyone finding this thread, Quark is causing the double door behavior. Just spotted it in the feature list today

http://quark.vazkii.us/#tweaks-double-door-opening
