### ISSUE TITLE
Blocks can be broken even if the land is claimed.

### ISSUE THREAD

**Issue by NightCraftHD** [GriefPrevention/GriefPrevention#836]
So, if i ( or someone else) claims land, people can still break blocks in that land. I have tried so many thing. Even reinstalling the plugin. But i can't find the answer. Pls help.

**Comment by RoboMWM** [comment]
If you're using powerranks, remove that.

**Comment by RoboMWM** [comment]
and if that fixes the issue please do let me know

**Comment by NightCraftHD** [comment]
but i don't know any other good rank systems

**Comment by bigpresh** [comment]
Was it the cause?  Did the issue go away when powerranks was removed?

**Comment by RoboMWM** [comment]
there are other ranks plugins. That one is not - just because it's popular doesn't mean it's good.

The developer supposedly updated it to fix the issue, but who knows if it's actually fixed since it isn't open source (until I bother to decompile it, which isn't gonna be anytime soon).

Another one to add to #528

**Comment by TomLewis** [comment]
CMI has a ranking system.
