### ISSUE TITLE
Allow players to place blocks during /siege

### ISSUE THREAD

**Issue by vastolf** [GriefPrevention/GriefPrevention#837]
As a player
I want to be able to place blocks/water/lava, etc during a siege
Because On my server we want to enable griefing during a /siege.

Right now when you attempt to place a block (even a block defined in the BreakableBlocks section of the config) in someone's claim when they are under /siege, you can't. Even a dirt block doesn't work. It'd be nice if I could enable block placing, and also define which blocks can be placed, especially in a way that allows me to enable lava/water placement.

**Is your feature request related to a problem? Please describe.**
I basically want to use GriefPrevention to stop people's stuff from being destroyed when they're not around to protect it. We allow griefing (anarchy server), but want people to have a chance to protect their stuff.

**Comment by RoboMWM** [comment]
soft blocks like dirt should be breakable, are you sure the materials you're putting there are in the Bukkit Material enum? If it is and it still doesn't work, that sounds like a bug.

But the intended design around siege is that it's not meant to be full on factions-esque warfare or permanent damage, but instead sufficient enough to push players to get outside of house and fight/PvP instead of being locked in inside - if that's what you want to encourage on your server.

So yea, suitable for an addon to allow this mechanic to be modified to fit your design.

**Comment by RoboMWM** [comment]
Do not delete issues please, instead posting the resolution or other related reason for closing for others who may have the same request would be eternally helpful.
