### ISSUE TITLE
TrustListHeader wrong print

### ISSUE THREAD

**Issue by Mabus13** [GriefPrevention/GriefPrevention#85]
TrustListHeader must be abowe.
But it printed below.

**Comment by Antivalent** [comment]
Confirmed for GriefPrevention 16.7.1. Also, the /claimlist header seems to appear below the actual list of land claims.

**Comment by RoboMWM** [comment]
Yea... just noticed this too... very odd, since I did not change anything there (if I did, it was definitely inadvertant).

**Comment by RoboMWM** [comment]
Ok, it seems that there's a mix of using `GriefPrevention#sendMessage` and `player#sendMessage`. The former schedules a task, hence why it's being printed at the end.

**Comment by RoboMWM** [comment]
~~Hmm, it also seems that the scheduler now operates as a stack instead of a queue, since there is no mixing of the two methods regarding `/claimslist`~~ though they are claiming otherwise in #spigot

Turns out, there's another `GriefPrevention#sendMessage` that uses just player#sendMessage. Fun.

Although I'd like to convert these all to `player#sendMessage`, it seems that the Messages enum relies on this sendMessage method to acquire the message to print...`

**Comment by RoboMWM** [comment]
Ok, now I see why he checked if the delay is 0 or less before scheduling... https://github.com/TechFortress/GriefPrevention/commit/39e1e13dda0cd68bed8cf684d421204e9505cbfd

**Comment by FrankHeijden** [comment]
already an ETA on this fix?

**Comment by RoboMWM** [comment]
It's already fixed as mentioned in referenced commit. 16.8 will be released as soon as I get a response on #207
