### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by koning12012** [GriefPrevention/GriefPrevention#851]
Hey

Other players can't use a shop with the ChestShop plugin
in a claim. How can i fix it?

**Comment by bigpreshkt** [comment]
You could start by providing some details - like, for instance, what happens when they try?

There's a reason there's an issue template asking all sorts of questions to try to glean the information which could be useful to be able to help.

EDIT: that said, the "Question" template you used doesn't really ask for much.  Perhaps we should tweak it to suggest giving as much info as possible.

**Comment by RoboMWM** [comment]
Can try using PrettySimpleShop, otherwise answer bigpresh's questions.

**Comment by RoboMWM** [comment]
ya, question template was kind of a catch-all for those using this issue tracker for general questions - which moreso is meant to provide users places to find answers. Not all will do it sure, but in a way it's to deal with "help vampires" though idk if that's the right term for most users who ask one-off questions. http://slash7.com/2006/12/22/vampires/

**Comment by koning12012** [comment]
> You could start by providing some details - like, for instance, what happens when they try?
> 
> There's a reason there's an issue template asking all sorts of questions to try to glean the information which could be useful to be able to help.
> 
> EDIT: that said, the "Question" template you used doesn't really ask for much. Perhaps we should tweak it to suggest giving as much info as possible.

There is no error, no message. Nothing.

**Comment by Jikoo** [comment]
> There is no error, no message. Nothing.

Sounds like not a GP issue then - if it were GP you'd at least see a message stating that you didn't have access.

**Comment by Jikoo** [comment]
Closing due to lack of response. Probably not a GP issue.
