### ISSUE TITLE
GriefPrevention loses all claims when Multiverse is used.

### ISSUE THREAD

**Issue by Konsider** [GriefPrevention/GriefPrevention#864]
.

**Comment by RoboMWM** [comment]
Need that server log.

Also, idk what you're doing with multiverse, but either they changed something drastically (which idk given no version or other plugins have been provided) or your manipulations are more involved than simple deletes/creates/etc. Please provide one way of reproducing cuz no, this hasn't happened to me.

**Comment by Konsider** [comment]
Hey, just giving you a report of a possible bug. That's the info I have provided. Feel free to delete it if it isn't good enough. Just trying to help you out.

**Comment by Jikoo** [comment]
If there's an error it should be fixed, but if it can't be reproduced we can't really help. Instead of closing the ticket you could provide the requested logs.

**Comment by Konsider** [comment]
It's ok. No interest in helping people with that attitude :D The ticket is closed.

**Comment by Jikoo** [comment]
I don't understand what your problem with a request for more information is - you filled out the rest of the ticket well, just not the logs - but oh well.

Without further information, based on my testing, OP probably is disabling worlds and not deleting them. When OP then loads the worlds again, GP has deleted claim data because the world does not exist. I know I've seen a ticket for this but can't seem to find it.

**Comment by Konsider** [comment]
Thanks for the info :D It might be an idea to make GP not delete any claim data or overwrite it without REALLY checking that is what should happen? People should be free to delete, remove, add, disable, etc worlds without fear of claims being deleted. If GP sees a world no longer exists, it should still keep the claim data!

Anyways, thanks again, and fire that first moron that answered the ticket :D Cheers!
