### ISSUE TITLE
Excessive RAM usage that steadily rises, with Paper

### ISSUE THREAD

**Issue by swim709** [GriefPrevention/GriefPrevention#871]
### What happened:
Started a brand new 1.16.1 with Paper build #68. Server starts with a very high % of RAM use, which then steadily rises. This occurs with now claims made and 0 players online. Disabling GriefPrevention stops the problem, and the server starts with a lower reasonable amount of RAM usage, which does not steadily rise even with someone logged in flying around.

### What was expected:
Similar RAM usage with and without GriefPrevention

### Steps to reproduce:
Use Paper with GriefPrevention?

### Server and GriefPrevention version:
git-Paper-47 (MC: 1.16.1)
GriefPrevention version 16.13.0

### Stack trace/error or server log
There are no errors.

### GriefPrevention config.yml

All configs are set to defaults.

### Debugging steps attempted
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Need a heap dump then to determine what objects are the cause of this usage.

**Comment by RoboMWM** [comment]
I'll reopen if you get a heap dump and evidence to suggest GP's at fault. Otherwise, see responses on spigot thread: https://www.spigotmc.org/threads/griefprevention.35615/page-330#post-3866306
https://www.spigotmc.org/threads/griefprevention.35615/page-330#post-3868368
and also that this was measured not from java itself but from the panel, which for all we know could be measuring container usage or other factors instead.

**Comment by swim709** [comment]
Forgive my ignorance.. but could you point me to some instructions as to how to generate the heap dump? I've Googled it a bit but can't seem to find anything definitive for Minecraft to go by.

________________________________

**Comment by RoboMWM** [comment]
It's been years since I've done one, but I think if you search around on spigot (or even papermc forums maybe) there should be instructions to using Java VisualVM or another tool.

Only thing is idk if you need your provider to do this if you're using a shared account/panel-only access. But - if you can reproduce on your local machine, then that'd be much easier.
