### ISSUE TITLE
More configuration options / more permission nodes

### ISSUE THREAD

**Issue by brr3** [GriefPrevention/GriefPrevention#887]
Hi! You have created a really useful plugin, however, it still leaves some things to be desired. A few things I'd like to see are  
* More configuration options such as the ability to disable all chat related commands (either with a permission or in the config)
  * Why? Because I already have a chat plugin that has these features, so I have been forced to disable the commands using command aliases (for example typing `/IgnorePlayer` is translated to "Command disabled" on my server). The problem with command aliases is that not all the commands displayed with the EssentialsX /help command are available to the player. On the most basic level, a permission node to disable these commands should be available.
* The permission node for buying and selling claim blocks should be separated into two nodes, one for buying and one for selling.
  * Why? I only want players to be able to buy claim blocks and not sell them. I have solved this using the command aliases like with `/IgnorePlayer`, but the simpler solution is with a permission node.
* A command for players to allow or disallow fire spread and damage inside of their claims.
  * Why? Just like players can choose whether to allow explosions or not inside of their claims, it would be cool if they could also choose if fire could spread and damage blocks or not.

**Comment by Jikoo** [comment]
* If you don't like the permissions for commands, you're welcome to use my [PermissionsSetup](https://github.com/Jikoo/PermissionsSetup) plugin to modify them. (Speaking of, oops, gotta push the update with api-version included.)
* Selling doesn't enable unless you set `ClaimBlocksSellValue` above 0, so you already can disable it. If you want to hide the command entirely, again, PermissionsSetup.
* Fire spread configuration is [already included in GPFlags](https://github.com/ShaneBeee/GriefPreventionFlags/wiki/Flags#nofirespread).

Closing because plugins already exist adding all requested features. If you do have suggestions in the future, please only include 1 type per ticket, it's a lot more manageable.
